In [1]:
import pandas as pd
from pathlib import Path
import sys

BASE_DIR = Path.cwd().parent
PROCESSED_DATA_DIR = BASE_DIR / 'data' / 'processed'
ANALISE_PARA_DASHBOARD = BASE_DIR / 'notebook' / 'dashboard_data'

# Carregando nosso dataset final, que é a única fonte de dados necessária a partir de agora
try:
    df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')
    print("Dataset final tratado carregado com sucesso!")
    print(f"Dimensões: {df_final.shape}")
except FileNotFoundError as e:
    print(f"Arquivo não encontrado {e}")

/tmp/ipykernel_8144/3018555840.py:11: DtypeWarning: Columns (1,5,6,7,23,24,26,27,29,30,36,37,43,69,73,74,85,97,112,113,122,146,148,149,151,152,161,167,171,181,203,205,218,229,269,282,297,345,361,370,371,372,373,374,375,376,418) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')

Dataset final tratado carregado com sucesso!
Dimensões: (17426, 525)

In [2]:
print(df_final.columns.tolist())

['id_participante', 'data_envio', 'idade', 'faixa_idade', 'genero', 'etnia', 'pcd', 'experiencia_prejudicada', 'prejudicado_acredita_nao_ser_afetado', 'prejudicado_raca_etnia', 'prejudicado_genero', 'prejudicado_pcd', 'uf_residencia', 'prejudicado_aspecto_qtd_oportunidades', 'prejudicado_aspecto_senioridade_vagas', 'prejudicado_aspecto_aprovacao_processos', 'prejudicado_aspecto_oportunidade_progressao', 'prejudicado_aspecto_velocidade_progressao', 'prejudicado_aspecto_cobranca_stress', 'prejudicado_aspecto_atencao_ideias', 'prejudicado_aspecto_relacao_trabalho', 'prejudicado_aspecto_relacao_integracao', 'regiao_residencia', 'prejudicado_aspectos_lista', 'uf_origem', 'regiao_origem', 'vive_no_brasil', 'pais_residencia', 'estado_residencia', 'vive_no_estado_formacao', 'estado_origem', 'nivel_ensino', 'area_formacao', 'situacao_trabalho', 'setor_atuacao', 'tamanho_empresa', 'atua_como_gestor', 'cargo_gestor', 'cargo_atual', 'nivel_hierarquico', 'faixa_salarial', 'experiencia_dados_anos', 'experiencia_ti_anos', 'satisfacao_trabalho', 'satisfacao_fator_remuneracao', 'satisfacao_fator_beneficios', 'satisfacao_fator_proposito', 'satisfacao_fator_flexibilidade', 'satisfacao_fator_ambiente', 'satisfacao_fator_aprendizado', 'satisfacao_fator_crescimento', 'satisfacao_fator_maturidade_empresa', 'satisfacao_fator_relacao_gestores', 'satisfacao_fator_reputacao_empresa', 'satisfacao_fator_desejo_mudar_area', 'motivos_insatisfacao', 'entrevistas_ultimos_6m', 'planos_mudar_emprego', 'criterios_escolha_emprego', 'criterio_escolha_remuneracao', 'criterio_escolha_beneficios', 'criterio_escolha_proposito', 'criterio_escolha_flexibilidade', 'criterio_escolha_ambiente', 'criterio_escolha_aprendizado', 'criterio_escolha_plano_carreira', 'criterio_escolha_maturidade_empresa', 'criterio_escolha_qualidade_gestores', 'criterio_escolha_reputacao_empresa', 'empresa_teve_layoff', 'modelo_trabalho_atual', 'modelo_trabalho_ideal', 'atitude_retorno_presencial', 'tamanho_equipe_dados', 'empresa_cargos_dados_lista', 'empresa_tem_analytics_engineer', 'empresa_tem_engenheiro_dados', 'empresa_tem_analista_dados', 'empresa_tem_cientista_dados', 'empresa_tem_dba', 'empresa_tem_analista_bi', 'empresa_tem_arquiteto_dados', 'empresa_tem_dpm', 'empresa_tem_business_analyst', 'empresa_tem_ml_engineer', 'gestor_responsabilidades_lista', 'gestor_resp_visao_longo_prazo', 'gestor_resp_treinamentos', 'gestor_resp_contratacao', 'gestor_resp_decisao_ferramentas', 'gestor_resp_head_engenharia', 'gestor_resp_head_analise_bi', 'gestor_resp_head_ia_ml', 'gestor_resp_atua_tecnico', 'gestor_resp_gestao_projetos', 'gestor_resp_gestao_produtos', 'gestor_resp_gestao_pessoas', 'desafios_gestor', 'gestor_desafio_contratar_talentos', 'gestor_desafio_reter_talentos', 'gestor_desafio_obter_investimento', 'gestor_desafio_gestao_remota', 'gestor_desafio_projetos_multiarea', 'gestor_desafio_qualidade_confiabilidade', 'gestor_desafio_volume_dados', 'gestor_desafio_gerar_valor_negocio', 'gestor_desafio_ml_em_producao', 'gestor_desafio_gerenciar_expectativas', 'gestor_desafio_manutencao_producao', 'gestor_desafio_inovar', 'gestor_desafio_garantir_roi', 'gestor_desafio_dividir_tempo_tecnico_gestao', 'ia_generativa_prioridade', 'ia_uso_empresa_lista', 'ia_uso_empresa_independente', 'ia_uso_empresa_centralizado', 'ia_uso_empresa_copilots', 'ia_uso_empresa_produtos_externos', 'ia_uso_empresa_produtos_internos', 'ia_uso_empresa_frente_negocio', 'ia_uso_empresa_nao_prioridade', 'ia_uso_empresa_nao_sabe', 'ia_motivos_nao_usar_lista', 'ia_motivo_nao_uso_falta_compreensao', 'ia_motivo_nao_uso_falta_confiabilidade', 'ia_motivo_nao_uso_incerteza_regulamentacao', 'ia_motivo_nao_uso_seguranca_privacidade', 'ia_motivo_nao_uso_roi_nao_comprovado', 'ia_motivo_nao_uso_dados_nao_prontos', 'ia_motivo_nao_uso_falta_expertise_recursos', 'ia_motivo_nao_uso_falta_apoio_direcao', 'ia_motivo_nao_uso_propriedade_intelectual', 'atuacao_funcao', 'atuacao_em_dados', 'fontes_dados_lista', 'fonte_dados_principal', '4.c.1_Dados relacionais (estruturados em bancos SQL)', '4.c.2_Dados armazenados em bancos NoSQL', '4.c.3_Imagens', '4.c.4_Textos/Documentos', '4.c.5_Vídeos', '4.c.6_Áudios', '4.c.7_Planilhas', '4.c.8_Dados georeferenciados', 'linguagens_usadas_dia_a_dia', 'linguagem_principal', 'linguagem_preferida', 'bancos_dados_usados_dia_a_dia', 'clouds_utilizadas', 'cloud_preferida', 'ferramentas_bi_usadas_dia_a_dia', 'bi_preferida', 'ia_uso_empresa_lista_pessoal', '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada', '4.l.2 Direcionamento centralizado do uso de AI generativa', '4.l.3 Desenvolvedores utilizando Copilots', '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais', '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores', '4.l.6 IA Generativa e LLMs como principal frente do negócio', '4.l.7 IA Generativa e LLMs não é prioridade', '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa', 'uso_ia_generativa_trabalho', 'ia_uso_pessoal_nenhuma', 'ia_uso_pessoal_gratuitas', 'ia_uso_pessoal_paga_propria', 'ia_uso_pessoal_empresa_paga', 'ia_uso_pessoal_copilot', 'objetivo_profissional', 'tipo_oportunidade_buscada', 'tempo_busca_emprego_meses', 'carreira_experiencia_processos_seletivos', 'rotina_engenheiro_dados', 'de_rotina_pipeline_codigo', 'de_rotina_etl_ferramentas', 'de_rotina_consultas_sql', 'de_rotina_integracao_plataformas', 'de_rotina_modelagem_arquitetura', 'de_rotina_manutencao_datalakes', 'de_rotina_modelagem_dados', 'de_rotina_qualidade_dados', 'de_rotina_nenhuma_das_opcoes', 'ferramentas_etl_engineer', 'de_etl_scripts_python', 'de_etl_sql_procedures', 'de_etl_airflow', 'de_etl_nifi', 'de_etl_luigi', 'de_etl_aws_glue', 'de_etl_talend', 'de_etl_pentaho', 'de_etl_alteryx', 'de_etl_stitch', 'de_etl_fivetran', 'de_etl_google_dataflow', 'de_etl_oracle_di', 'de_etl_ibm_datastage', 'de_etl_sap_bw', 'de_etl_ssis', 'de_etl_sas_di', 'de_etl_qlik_sense', 'de_etl_knime', 'de_etl_databricks', 'de_etl_nenhuma', 'de_empresa_possui_data_lake', 'de_empresa_tecnologia_data_lake', 'de_empresa_possui_data_warehouse', 'de_empresa_tecnologia_data_warehouse', 'de_ferramentas_qualidade_dados_lista', 'de_maior_tempo_gasto', 'de_maior_tempo_pipelines_codigo', 'de_maior_tempo_etl_ferramentas', 'de_maior_tempo_consultas_sql', 'de_maior_tempo_integracao_plataformas', 'de_maior_tempo_modelagem_arquitetura', 'de_maior_tempo_manutencao_datalakes', 'de_maior_tempo_modelagem_dados', 'de_maior_tempo_qualidade_dados', 'de_maior_tempo_nenhuma_das_opcoes', 'rotina_analista_dados', 'da_rotina_analise_codigo', 'da_rotina_dashboards_bi', 'da_rotina_consultas_sql', 'da_rotina_extracao_api', 'da_rotina_estatistica_testes', 'da_rotina_manutencao_etl', 'da_rotina_modelagem_dados', 'da_rotina_manutencao_planilhas', 'da_rotina_estatistica_avancada', 'da_rotina_nenhuma_das_opcoes', 'ferramentas_etl_analyst', 'da_etl_scripts_python', 'da_etl_sql_procedures', 'da_etl_airflow', 'da_etl_nifi', 'da_etl_luigi', 'da_etl_aws_glue', 'da_etl_talend', 'da_etl_pentaho', 'da_etl_alteryx', 'da_etl_stitch', 'da_etl_fivetran', 'da_etl_google_dataflow', 'da_etl_oracle_di', 'da_etl_ibm_datastage', 'da_etl_sap_bw', 'da_etl_ssis', 'da_etl_sas_di', 'da_etl_qlik_sense', 'da_etl_knime', 'da_etl_databricks', 'da_etl_nenhuma', 'da_ferramentas_autonomia_negocios_lista', 'da_autonomia_ferramentas_automl', 'da_autonomia_ferramentas_point_and_click', 'da_autonomia_ferramentas_product_insights', 'da_autonomia_ferramentas_crm_analytics', 'da_autonomia_ferramentas_nenhuma', 'da_autonomia_ferramentas_nao_sabe', 'da_maior_tempo_gasto', 'da_maior_tempo_analise_codigo', 'da_maior_tempo_dashboards_bi', 'da_maior_tempo_consultas_sql', 'da_maior_tempo_extracao_api', 'da_maior_tempo_estatistica_testes', 'da_maior_tempo_manutencao_etl', 'da_maior_tempo_modelagem_dados', 'da_maior_tempo_manutencao_planilhas', 'da_maior_tempo_estatistica_avancada', 'da_maior_tempo_nenhuma_das_opcoes', 'rotina_cientista_dados', 'ds_rotina_estudos_ad_hoc', 'ds_rotina_coleta_limpeza', 'ds_rotina_contato_negocios', 'ds_rotina_desenvolvimento_ml', 'ds_rotina_ml_em_producao', 'ds_rotina_manutencao_ml', 'ds_rotina_dashboards_bi', 'ds_rotina_estatistica_avancada', 'ds_rotina_manutencao_etl', 'ds_rotina_feature_store_mlops', 'ds_rotina_infraestrutura', 'ds_rotina_treino_llm', 'tecnicas_ml_cientista', 'ds_tecnica_regressao', 'ds_tecnica_classificacao_arvores_redes', 'ds_tecnica_sistemas_recomendacao', 'ds_tecnica_estatistica_bayesiana', 'ds_tecnica_nlp', 'ds_tecnica_estatistica_classica', 'ds_tecnica_markov_hmm', 'ds_tecnica_clusterizacao', 'ds_tecnica_series_temporais', 'ds_tecnica_reinforcement_learning', 'ds_tecnica_deteccao_fraude', 'ds_tecnica_visao_computacional', 'ds_tecnica_deteccao_churn', 'ds_tecnica_llm', 'tecnologias_cientista', 'ds_tecnologia_ferramentas_bi', 'ds_tecnologia_planilhas', 'ds_tecnologia_dev_local', 'ds_tecnologia_dev_nuvem', 'ds_tecnologia_automl', 'ds_tecnologia_etl', 'ds_tecnologia_plataformas_ml', 'ds_tecnologia_feature_store', 'ds_tecnologia_controle_versao', 'ds_tecnologia_data_apps', 'ds_tecnologia_estatistica_avancada', 'ds_maior_tempo_gasto', 'ds_maior_tempo_estudos_ad_hoc', 'ds_maior_tempo_coleta_limpeza', 'ds_maior_tempo_contato_negocios', 'ds_maior_tempo_desenvolvimento_ml', 'ds_maior_tempo_ml_em_producao', 'ds_maior_tempo_manutencao_ml', 'ds_maior_tempo_dashboards_bi', 'ds_maior_tempo_estatistica_avancada', 'ds_maior_tempo_manutencao_etl', 'ds_maior_tempo_feature_store_mlops', 'ds_maior_tempo_infraestrutura', 'ds_maior_tempo_treino_llm', 'salario_medio_mensal', 'grupo_cargo', 'experiencia_anos_num', 'usa_.net', 'usa_c_c++_c#', 'usa_java', 'usa_javascript', 'usa_julia', 'usa_matlab', 'usa_nenhuma', 'usa_não_utilizo_linguagem_de_programação_no_trabalho', 'usa_php', 'usa_python', 'usa_r', 'usa_rust', 'usa_sas_stata', 'usa_sql', 'usa_scala', 'usa_visual_basic_vba', 'ano', 'prejudicado_motivo_raca_etnia', 'prejudicado_motivo_genero', 'prejudicado_motivo_pcd', 'mudou_de_estado', 'insatisfacao_fator_falta_crescimento', 'insatisfacao_fator_salario_defasado', 'insatisfacao_fator_relacao_gestor', 'insatisfacao_fator_desejo_mudar_area', 'insatisfacao_fator_beneficios', 'insatisfacao_fator_ambiente_ruim', 'insatisfacao_fator_baixa_maturidade_empresa', 'fonte_dados_principal_relacionais', 'fonte_dados_principal_nosql', 'fonte_dados_principal_imagens', 'fonte_dados_principal_textos', 'fonte_dados_principal_videos', 'fonte_dados_principal_audios', 'fonte_dados_principal_planilhas', 'fonte_dados_principal_geo', 'cloud_preferida_lista', 'ia_uso_empresa_independente.1', 'ia_uso_empresa_centralizado.1', 'ia_uso_empresa_copilots.1', 'ia_uso_empresa_produtos_externos.1', 'ia_uso_empresa_produtos_internos.1', 'ia_uso_empresa_frente_negocio.1', 'ia_uso_empresa_nao_prioridade.1', 'ia_uso_empresa_nao_sabe.1', 'de_rotina_lista', 'de_ferramentas_etl_lista', 'da_rotina_lista', 'da_ferramentas_etl_lista', 'ds_rotina_lista', 'ds_tecnicas_lista', 'ds_tecnologias_lista', 'de_qualidade_great_expectations', 'de_qualidade_dbt', 'de_qualidade_aws_deequ', 'de_qualidade_apache_griffin', 'de_qualidade_datafold', 'de_qualidade_amundsen', 'de_qualidade_monte_carlo', 'de_qualidade_soda', 'de_qualidade_big_eye', 'de_qualidade_data_band', 'de_qualidade_anomalo', 'de_qualidade_metaplane', 'de_qualidade_acceldata', 'linguagem_principal_sql', 'linguagem_principal_r', 'linguagem_principal_python', 'linguagem_principal_c_cplusplus_csharp', 'linguagem_principal_dotnet', 'linguagem_principal_java', 'linguagem_principal_julia', 'linguagem_principal_sas_stata', 'linguagem_principal_vba', 'linguagem_principal_scala', 'linguagem_principal_matlab', 'linguagem_principal_php', 'linguagem_principal_javascript', 'linguagem_principal_nenhuma', 'de_qualidade_dados_great_expectations', 'de_qualidade_dados_dbt', 'de_qualidade_dados_aws_deequ', 'de_qualidade_dados_apache_griffin', 'de_qualidade_dados_datafold', 'de_qualidade_dados_amundsen', 'de_qualidade_dados_monte_carlo', 'de_qualidade_dados_soda', 'de_qualidade_dados_big_eye', 'de_qualidade_dados_data_band', 'de_qualidade_dados_anomalo', 'de_qualidade_dados_metaplane', 'de_qualidade_dados_acceldata', 'ds_tecnologia_nenhuma', 'dh_iniciativas_acessadas_lista', 'dh_iniciativa_blog', 'dh_iniciativa_podcast', 'dh_iniciativa_newsletter', 'dh_iniciativa_slack', 'dh_iniciativa_youtube', 'dh_iniciativa_nao_conhecia', 'usa_linguagem_net', 'usa_linguagem_c_c++_c#', 'usa_linguagem_java', 'usa_linguagem_javascript', 'usa_linguagem_julia', 'usa_linguagem_matlab', 'usa_linguagem_nenhuma', 'usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho', 'usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas', 'usa_linguagem_php', 'usa_linguagem_python', 'usa_linguagem_r', 'usa_linguagem_rust', 'usa_linguagem_sas_stata', 'usa_linguagem_sql', 'usa_linguagem_scala', 'usa_linguagem_visual_basic_vba', 'usa_bi_alteryx', 'usa_bi_amazon_quicksight', 'usa_bi_amazon_quicksight.1', 'usa_bi_amplitude', 'usa_bi_aplicação_própria_da_empresa_para_bi_dashboards', 'usa_bi_birst', 'usa_bi_bla', 'usa_bi_chartio', 'usa_bi_cortex', 'usa_bi_desenvolvemos_bi_próprio', 'usa_bi_desenvolvemos_em_javascript', 'usa_bi_elasticsearch', 'usa_bi_excel', 'usa_bi_fazemos_todas_as_análises_utilizando_apenas_excel_ou_planilhas_do_google', 'usa_bi_ferramenta_própria', 'usa_bi_google_data_studio', 'usa_bi_grafana', 'usa_bi_hex', 'usa_bi_ibm_analytics_cognos', 'usa_bi_informatica_dei___informatica_power_center', 'usa_bi_jupyter_notebook', 'usa_bi_kibana', 'usa_bi_knime', 'usa_bi_looker', 'usa_bi_looker_studio_antigo_google_data_studio', 'usa_bi_metabase', 'usa_bi_microstrategy', 'usa_bi_microsoft_analysis_services', 'usa_bi_microsoft_powerbi', 'usa_bi_mode', 'usa_bi_nao_atuo_na_area_de_dados', 'usa_bi_nenhum', 'usa_bi_nenhuma', 'usa_bi_não_utilizo', 'usa_bi_não_utilizo_ferramentas_de_bi', 'usa_bi_não_utilizo_nenhuma_ferramenta_de_bi_no_trabalho', 'usa_bi_nāo_estou_trabalhando_com_ti_no_momento', 'usa_bi_oracle_business_intelligence', 'usa_bi_outra_opção', 'usa_bi_pacotes_python', 'usa_bi_pandas', 'usa_bi_pentaho', 'usa_bi_plotly', 'usa_bi_python_seaborn_matplotlib', 'usa_bi_qlik_view_qlik_sense', 'usa_bi_rstudio', 'usa_bi_redash', 'usa_bi_reports', 'usa_bi_retool', 'usa_bi_rmarkdown', 'usa_bi_sap_business_objects_sap_analytics', 'usa_bi_sas_visual_analytics', 'usa_bi_sql_databricks', 'usa_bi_ssis', 'usa_bi_salesforce_datorama', 'usa_bi_salesforce_einstein_analytics', 'usa_bi_senior', 'usa_bi_shiny', 'usa_bi_shiny_apps', 'usa_bi_sigma', 'usa_bi_sisense', 'usa_bi_sistemas_de_supervisório_scada_ftview___wincc___cimplicity', 'usa_bi_solução_da_própria_empresa', 'usa_bi_spinklr', 'usa_bi_streamlit', 'usa_bi_superset', 'usa_bi_synapsis_analytics', 'usa_bi_tibco_spotfire', 'usa_bi_tableau', 'usa_bi_talend', 'usa_bi_tensorflow', 'usa_bi_totvs_rm', 'usa_bi_tudo_de_apache', 'usa_bi_viewb', 'usa_bi_wavefront', 'usa_bi_zoho', 'usa_bi_zoho_analytics', 'usa_bi_estudante', 'usa_bi_nda', 'usa_bi_nenhuma.1', 'usa_bi_nexbi', 'usa_bi_não_utilizo_ferramentas_de_bi_ainda', 'usa_bi_streamlit.1']

In [3]:
Path('dashboard_data').mkdir(exist_ok=True)
print("Pasta 'dashboard_data/' pronta para receber os arquivos de análise.")

Pasta 'dashboard_data/' pronta para receber os arquivos de análise.

In [4]:
df_final

,id_participante,data_envio,idade,faixa_idade,genero,etnia,pcd,experiencia_prejudicada,prejudicado_acredita_nao_ser_afetado,prejudicado_raca_etnia,...,usa_bi_viewb,usa_bi_wavefront,usa_bi_zoho,usa_bi_zoho_analytics,usa_bi_estudante,usa_bi_nda,usa_bi_nenhuma.1,usa_bi_nexbi,usa_bi_não_utilizo_ferramentas_de_bi_ainda,usa_bi_streamlit.1
0,reb94rv0msth7q4nreb94riaq80iz3yi,2024-10-16 11:19:17,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,2024-10-16 20:45:31,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,2024-10-17 18:10:59,18.0,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,2024-10-22 18:03:00,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,2024-10-23 01:33:23,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17421,07nvo8cdy377a46gon207nvjebwe65zg,NaN,40.0,40-44,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17422,01mqnby32u01pg3nuj6vipp4mc06s8pg,NaN,27.0,25-29,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17423,01fncs8qbhl9zx01fncs8rqib2zl3d18,NaN,24.0,22-24,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17424,075h3v2z19if04yn7o075h3vhifl38rw,NaN,38.0,35-39,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17425,037usz1h2yip96dgil4mhj037uszw1gk,NaN,27.0,25-29,Feminino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

## 1 - TABELA DE EVOLUÇÃO SALARIAL POR CARGO

In [5]:
print(df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack())

grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [6]:
evolucao_salario_cargo = df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack()

In [7]:
print('Tabela gerada: ')
print(evolucao_salario_cargo)

Tabela gerada:
grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [8]:
evolucao_salario_cargo.to_csv(ANALISE_PARA_DASHBOARD/'analise_evolucao_salario_cargo.csv')
print(f'tabela evoluação salário por cargo criada e exportada para {ANALISE_PARA_DASHBOARD}')

tabela evoluação salário por cargo criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

## 2 - TABELA DE EVOLUÇÃO SALARIAL POR SENIORIDADE

In [9]:
evolucao_salario_senioridade = df_final.groupby(['ano', 'nivel_hierarquico'])['salario_medio_mensal'].mean().round(2).unstack()

In [10]:
evolucao_salario_senioridade

nivel_hierarquico   Júnior    Pleno    Sênior
ano
2021               3876.49  7609.92  12401.89
2022               3928.64  7961.82  12848.50
2023               3919.75  7533.55  13577.68
2024               4166.96  8048.79  14506.23

In [11]:
evolucao_salario_senioridade.reset_index().to_csv(ANALISE_PARA_DASHBOARD/'analise_evolucao_salario_senioridade.csv', index=False)
print(f'Tabela de evolução do salário médio por senioridade criada e exportada para {ANALISE_PARA_DASHBOARD}')

Tabela de evolução do salário médio por senioridade criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

##### Pergunta "4" das hipóteses respondidas ✅

## 3 - TABELA DE POPULARIDADE DE LINGUAGENS USADAS POR ANO

In [12]:
colunas_linguagens = [col for col in df_final.columns if col.startswith('usa_linguagem_')]

In [13]:
colunas_linguagens

['usa_linguagem_net',
 'usa_linguagem_c_c++_c#',
 'usa_linguagem_java',
 'usa_linguagem_javascript',
 'usa_linguagem_julia',
 'usa_linguagem_matlab',
 'usa_linguagem_nenhuma',
 'usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho',
 'usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas',
 'usa_linguagem_php',
 'usa_linguagem_python',
 'usa_linguagem_r',
 'usa_linguagem_rust',
 'usa_linguagem_sas_stata',
 'usa_linguagem_sql',
 'usa_linguagem_scala',
 'usa_linguagem_visual_basic_vba']

In [14]:
popularidade_linguagens = df_final.groupby('ano')[colunas_linguagens].sum()

In [15]:
popularidade_linguagens

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,42,64,84,174,8,15,788,0,162,38,1346,306,0,77,1487,89,160
2022,33,52,106,194,6,25,1290,0,319,39,2089,385,0,123,2367,119,218
2023,40,70,113,282,8,30,1521,0,305,56,2825,401,7,151,3156,131,285
2024,31,46,94,223,6,20,1628,165,0,34,2935,342,12,130,3146,126,215

In [16]:
##porcentagem
total_respondentes_ano = df_final['ano'].value_counts()
popularidade_linguagensa_pct = popularidade_linguagens.div(total_respondentes_ano, axis=0).mul(100).round(2)

In [17]:
popularidade_linguagensa_pct

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,1.59,2.42,3.18,6.58,0.30,0.57,29.79,0.00,6.12,1.44,50.89,11.57,0.00,2.91,56.22,3.36,6.05
2022,0.77,1.22,2.48,4.54,0.14,0.59,30.20,0.00,7.47,0.91,48.91,9.01,0.00,2.88,55.42,2.79,5.10
2023,0.76,1.32,2.13,5.33,0.15,0.57,28.74,0.00,5.76,1.06,53.37,7.58,0.13,2.85,59.63,2.47,5.38
2024,0.59,0.88,1.80,4.27,0.12,0.38,31.21,3.16,0.00,0.65,56.26,6.56,0.23,2.49,60.30,2.42,4.12

In [18]:
total_respondentes_ano

ano
2023    5293
2024    5217
2022    4271
2021    2645
Name: count, dtype: int64

In [19]:
popularidade_linguagensa_pct.to_csv(ANALISE_PARA_DASHBOARD/'analise_popularidade_linguagens_pct.csv')
print(f'Tabela gerada de % de uso da linguagem')

Tabela gerada de % de uso da linguagem

##### Pergunta número "8" das hipóteses respondida ✅

## 4 - QUAL A EVOLUÇÃO DOS MODELOS DE TRABALHO (REMOTO, HÍBRIDO, PRESENCIAL)

In [20]:
print(df_final['modelo_trabalho_atual'].value_counts())

modelo_trabalho_atual
Modelo 100% remoto                                                                                                7447
Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente)    3378
Modelo 100% presencial                                                                                            2492
Modelo híbrido com dias fixos de trabalho presencial                                                              2358
Name: count, dtype: int64

In [21]:
df_final['modelo_trabalho_atual'].fillna('Não informado', inplace=True)

mapa_modelos = {
  "Modelo 100% remoto": "Remoto",
  "Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente)": "Híbrido Flexível",
  "Modelo 100% presencial":"Presencial",
  "Modelo híbrido com dias fixos de trabalho presencial": "Híbrido Fixo",
  "Não informado": "Não informado"
}

/tmp/ipykernel_8144/3910453653.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['modelo_trabalho_atual'].fillna('Não informado', inplace=True)

In [22]:
modelos_curtos = df_final['modelo_trabalho_atual'].replace(mapa_modelos)

In [23]:
df_final['modelo_trabalho_atual'].isna().sum()

np.int64(0)

In [24]:
pd.crosstab(df_final['ano'], df_final['modelo_trabalho_atual'], normalize='index').mul(100).round(2)

modelo_trabalho_atual,Modelo 100% presencial,Modelo 100% remoto,Modelo híbrido com dias fixos de trabalho presencial,Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente),Não informado
ano,,,,,
2021,12.40,50.47,9.11,17.43,10.59
2022,13.63,39.55,11.17,22.15,13.51
2023,14.93,41.58,14.93,18.36,10.20
2024,15.18,42.59,16.29,19.15,6.79

In [25]:
df_final['modelo_trabalho_limpo'] = df_final['modelo_trabalho_atual'].replace(mapa_modelos)

In [26]:
evolucao_modelo_trabalho_pct = pd.crosstab(df_final['ano'], df_final['modelo_trabalho_limpo'], normalize='index').mul(100).round(2)

In [27]:
evolucao_modelo_trabalho_pct

modelo_trabalho_limpo,Híbrido Fixo,Híbrido Flexível,Não informado,Presencial,Remoto
ano,,,,,
2021,9.11,17.43,10.59,12.40,50.47
2022,11.17,22.15,13.51,13.63,39.55
2023,14.93,18.36,10.20,14.93,41.58
2024,16.29,19.15,6.79,15.18,42.59

In [28]:
evolucao_modelo_trabalho_pct.to_csv(ANALISE_PARA_DASHBOARD/'analise_evolucao_modelo_trabalho_pct.csv')

##### Hipótese "18" respondida ✅

## 5 EXISTE DIFERENÇA SALARIAL POR GÊNERO (GENDER PAY GAP)?

In [29]:
print('valores coluna gênero')
print(df_final['genero'].value_counts())

valores coluna gênero
genero
Masculino               13281
Feminino                 4068
Prefiro não informar       43
Outro                      25
Name: count, dtype: int64

In [40]:
analise_genero_senioridade = df_final.groupby(['ano', 'nivel_hierarquico', 'genero'])['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [41]:
analise_genero_senioridade.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [42]:
analise_genero_senioridade[['salario_medio', 'salario_mediana']] = analise_genero_senioridade[['salario_medio', 'salario_mediana']].round(2)

In [47]:
print("\nTabela gerada (Estatísticas Salariais por Ano e Gênero):")
print(analise_genero_senioridade.unstack(level='genero'))

Tabela gerada (Estatísticas Salariais por Ano e Gênero):
                       salario_medio                                           \
genero                      Feminino Masculino     Outro Prefiro não informar
ano  nivel_hierarquico
2021 Júnior                  4149.79   3793.73   3833.83                  NaN
     Pleno                   7492.87   7591.93  20000.50                  NaN
     Sênior                 10612.20  12749.48       NaN                  NaN
2022 Júnior                  3972.92   3926.46       NaN              3000.38
     Pleno                   7681.86   8069.58       NaN              7625.50
     Sênior                 11168.95  13288.24       NaN             10000.50
2023 Júnior                  3706.17   4001.23   1500.50              5833.83
     Pleno                   7464.89   7564.01   6125.50              6750.50
     Sênior                 12355.56  13863.08   8500.50             31000.62
2024 Júnior                  4161.64   4118.46       NaN             14667.33
     Pleno                   7817.44   8135.19   7000.50              8000.50
     Sênior                 12513.94  15059.10   9000.50             15250.58

                       salario_mediana                     \
genero                        Feminino Masculino    Outro
ano  nivel_hierarquico
2021 Júnior                     3500.5    3500.5   5000.5
     Pleno                      7000.5    7000.5  20000.5
     Sênior                    10000.5   10000.5      NaN
2022 Júnior                     3500.5    3500.5      NaN
     Pleno                      7000.5    7000.5      NaN
     Sênior                    10000.5   10000.5      NaN
2023 Júnior                     3500.5    3500.5   1500.5
     Pleno                      7000.5    7000.5   6000.5
     Sênior                    10000.5   14000.5   8500.5
2024 Júnior                     3500.5    3500.5      NaN
     Pleno                      7000.5    7000.5   7000.5
     Sênior                    10000.5   14000.5  10000.5

                                            contagem                  \
genero                 Prefiro não informar Feminino Masculino Outro
ano  nivel_hierarquico
2021 Júnior                             NaN    144.0     474.0   3.0
     Pleno                              NaN    131.0     525.0   2.0
     Sênior                             NaN     94.0     484.0   NaN
2022 Júnior                          2000.5    272.0     743.0   NaN
     Pleno                           8500.5    295.0     760.0   NaN
     Sênior                         10000.5    187.0     709.0   NaN
2023 Júnior                          7000.5    299.0     743.0   1.0
     Pleno                           6000.5    337.0    1047.0   4.0
     Sênior                         35000.5    307.0    1106.0   2.0
2024 Júnior                          2500.5    242.0     623.0   NaN
     Pleno                           7000.5    366.0    1006.0   2.0
     Sênior                         10000.5    335.0    1229.0   3.0


genero                 Prefiro não informar
ano  nivel_hierarquico
2021 Júnior                             NaN
     Pleno                              NaN
     Sênior                             NaN
2022 Júnior                             4.0
     Pleno                              4.0
     Sênior                             1.0
2023 Júnior                             3.0
     Pleno                              4.0
     Sênior                             4.0
2024 Júnior                             3.0
     Pleno                              3.0
     Sênior                             6.0

In [50]:
media_pivot_senioridade = analise_genero_senioridade['salario_medio'].unstack(level='genero')

In [54]:
if 'Masculino' in media_pivot_senioridade.columns and 'Feminino' in media_pivot_senioridade.columns:
  media_pivot_senioridade['pay_gap_percentual'] = \
    ((media_pivot_senioridade['Masculino'] - media_pivot_senioridade['Feminino']) / media_pivot_senioridade['Masculino']) * 100
  
  pay_gap_por_nivel = media_pivot_senioridade[['Masculino', 'Feminino', 'pay_gap_percentual']].round(2)

  print("\nTabela Pay Gap por Nível (Diferença % entre Salário Médio Masculino e Feminino):")
  print(pay_gap_por_nivel)

else:
  print("\nNão foi possível calcular o Pay Gap por nível (colunas 'Masculino' ou 'Feminino' não encontradas).")

Tabela Pay Gap por Nível (Diferença % entre Salário Médio Masculino e Feminino):
genero                  Masculino  Feminino  pay_gap_percentual
ano  nivel_hierarquico
2021 Júnior               3793.73   4149.79               -9.39
     Pleno                7591.93   7492.87                1.30
     Sênior              12749.48  10612.20               16.76
2022 Júnior               3926.46   3972.92               -1.18
     Pleno                8069.58   7681.86                4.80
     Sênior              13288.24  11168.95               15.95
2023 Júnior               4001.23   3706.17                7.37
     Pleno                7564.01   7464.89                1.31
     Sênior              13863.08  12355.56               10.87
2024 Júnior               4118.46   4161.64               -1.05
     Pleno                8135.19   7817.44                3.91
     Sênior              15059.10  12513.94               16.90

In [87]:
analise_genero_senioridade.to_csv(ANALISE_PARA_DASHBOARD/'05_analise_salario_por_genero_senioridade_stats.csv')
print(f"\n>> Tabela detalhada por gênero e senioridade salva em {ANALISE_PARA_DASHBOARD}")

>> Tabela detalhada por gênero e senioridade salva em /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

In [88]:
if 'pay_gap_por_nivel' in locals(): 
  # Resetamos o índice para que 'ano' e 'nivel_hierarquico' virem colunas
  pay_gap_por_nivel.to_csv(ANALISE_PARA_DASHBOARD/'05_analise_pay_gap_percentual_por_nivel.csv')
  print(f">> Tabela do Pay Gap percentual por nível salva em {ANALISE_PARA_DASHBOARD}'/analise_pay_gap_percentual_por_nivel.csv'\n")

>> Tabela do Pay Gap percentual por nível salva em /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data'/analise_pay_gap_percentual_por_nivel.csv'