In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import sys

BASE_DIR = Path.cwd().parent
PROCESSED_DATA_DIR = BASE_DIR / 'data' / 'processed'
ANALISE_PARA_DASHBOARD = BASE_DIR / 'notebook' / 'dashboard_data'

# Carregando nosso dataset final, que é a única fonte de dados necessária a partir de agora
try:
    df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')
    print("Dataset final tratado carregado com sucesso!")
    print(f"Dimensões: {df_final.shape}")
except FileNotFoundError as e:
    print(f"Arquivo não encontrado {e}")

/tmp/ipykernel_14657/3258992335.py:12: DtypeWarning: Columns (1,5,6,7,23,24,26,27,29,30,36,43,69,74,112,113,122,146,148,149,151,152,161,167,171,181,203,205,218,229,269,282,297,345,361,370,371,372,373,374,375,376,418) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')

Dataset final tratado carregado com sucesso!
Dimensões: (17426, 456)

In [2]:
print(df_final.columns.tolist())
print(len(df_final.columns))

['id_participante', 'data_envio', 'idade', 'faixa_idade', 'genero', 'etnia', 'pcd', 'experiencia_prejudicada', 'prejudicado_acredita_nao_ser_afetado', 'prejudicado_raca_etnia', 'prejudicado_genero', 'prejudicado_pcd', 'uf_residencia', 'prejudicado_aspecto_qtd_oportunidades', 'prejudicado_aspecto_senioridade_vagas', 'prejudicado_aspecto_aprovacao_processos', 'prejudicado_aspecto_oportunidade_progressao', 'prejudicado_aspecto_velocidade_progressao', 'prejudicado_aspecto_cobranca_stress', 'prejudicado_aspecto_atencao_ideias', 'prejudicado_aspecto_relacao_trabalho', 'prejudicado_aspecto_relacao_integracao', 'regiao_residencia', 'prejudicado_aspectos_lista', 'uf_origem', 'regiao_origem', 'vive_no_brasil', 'pais_residencia', 'estado_residencia', 'vive_no_estado_formacao', 'estado_origem', 'nivel_ensino', 'area_formacao', 'situacao_trabalho', 'setor_atuacao', 'tamanho_empresa', 'atua_como_gestor', 'cargo_gestor', 'cargo_atual', 'nivel_hierarquico', 'faixa_salarial', 'experiencia_dados_anos', 'experiencia_ti_anos', 'satisfacao_trabalho', 'satisfacao_fator_remuneracao', 'satisfacao_fator_beneficios', 'satisfacao_fator_proposito', 'satisfacao_fator_flexibilidade', 'satisfacao_fator_ambiente', 'satisfacao_fator_aprendizado', 'satisfacao_fator_crescimento', 'satisfacao_fator_maturidade_empresa', 'satisfacao_fator_relacao_gestores', 'satisfacao_fator_reputacao_empresa', 'satisfacao_fator_desejo_mudar_area', 'motivos_insatisfacao', 'entrevistas_ultimos_6m', 'planos_mudar_emprego', 'criterios_escolha_emprego', 'criterio_escolha_remuneracao', 'criterio_escolha_beneficios', 'criterio_escolha_proposito', 'criterio_escolha_flexibilidade', 'criterio_escolha_ambiente', 'criterio_escolha_aprendizado', 'criterio_escolha_plano_carreira', 'criterio_escolha_maturidade_empresa', 'criterio_escolha_qualidade_gestores', 'criterio_escolha_reputacao_empresa', 'empresa_teve_layoff', 'modelo_trabalho_atual', 'modelo_trabalho_ideal', 'atitude_retorno_presencial', 'tamanho_equipe_dados', 'empresa_cargos_dados_lista', 'empresa_tem_analytics_engineer', 'empresa_tem_engenheiro_dados', 'empresa_tem_analista_dados', 'empresa_tem_cientista_dados', 'empresa_tem_dba', 'empresa_tem_analista_bi', 'empresa_tem_arquiteto_dados', 'empresa_tem_dpm', 'empresa_tem_business_analyst', 'empresa_tem_ml_engineer', 'gestor_responsabilidades_lista', 'gestor_resp_visao_longo_prazo', 'gestor_resp_treinamentos', 'gestor_resp_contratacao', 'gestor_resp_decisao_ferramentas', 'gestor_resp_head_engenharia', 'gestor_resp_head_analise_bi', 'gestor_resp_head_ia_ml', 'gestor_resp_atua_tecnico', 'gestor_resp_gestao_projetos', 'gestor_resp_gestao_produtos', 'gestor_resp_gestao_pessoas', 'desafios_gestor', 'gestor_desafio_contratar_talentos', 'gestor_desafio_reter_talentos', 'gestor_desafio_obter_investimento', 'gestor_desafio_gestao_remota', 'gestor_desafio_projetos_multiarea', 'gestor_desafio_qualidade_confiabilidade', 'gestor_desafio_volume_dados', 'gestor_desafio_gerar_valor_negocio', 'gestor_desafio_ml_em_producao', 'gestor_desafio_gerenciar_expectativas', 'gestor_desafio_manutencao_producao', 'gestor_desafio_inovar', 'gestor_desafio_garantir_roi', 'gestor_desafio_dividir_tempo_tecnico_gestao', 'ia_generativa_prioridade', 'ia_uso_empresa_lista', 'ia_uso_empresa_independente', 'ia_uso_empresa_centralizado', 'ia_uso_empresa_copilots', 'ia_uso_empresa_produtos_externos', 'ia_uso_empresa_produtos_internos', 'ia_uso_empresa_frente_negocio', 'ia_uso_empresa_nao_prioridade', 'ia_uso_empresa_nao_sabe', 'ia_motivos_nao_usar_lista', 'ia_motivo_nao_uso_falta_compreensao', 'ia_motivo_nao_uso_falta_confiabilidade', 'ia_motivo_nao_uso_incerteza_regulamentacao', 'ia_motivo_nao_uso_seguranca_privacidade', 'ia_motivo_nao_uso_roi_nao_comprovado', 'ia_motivo_nao_uso_dados_nao_prontos', 'ia_motivo_nao_uso_falta_expertise_recursos', 'ia_motivo_nao_uso_falta_apoio_direcao', 'ia_motivo_nao_uso_propriedade_intelectual', 'atuacao_funcao', 'atuacao_em_dados', 'fontes_dados_lista', 'fonte_dados_principal', '4.c.1_Dados relacionais (estruturados em bancos SQL)', '4.c.2_Dados armazenados em bancos NoSQL', '4.c.3_Imagens', '4.c.4_Textos/Documentos', '4.c.5_Vídeos', '4.c.6_Áudios', '4.c.7_Planilhas', '4.c.8_Dados georeferenciados', 'linguagens_usadas_dia_a_dia', 'linguagem_principal', 'linguagem_preferida', 'bancos_dados_usados_dia_a_dia', 'clouds_utilizadas', 'cloud_preferida', 'ferramentas_bi_usadas_dia_a_dia', 'bi_preferida', 'ia_uso_empresa_lista_pessoal', '4.l.1 Colaboradores usando AI generativa de forma independente e descentralizada', '4.l.2 Direcionamento centralizado do uso de AI generativa', '4.l.3 Desenvolvedores utilizando Copilots', '4.l.4 AI Generativa e LLMs para melhorar produtos externos para os clientes finais', '4.l.5 AI Generativa e LLMs para melhorar produtos internos para os colaboradores', '4.l.6 IA Generativa e LLMs como principal frente do negócio', '4.l.7 IA Generativa e LLMs não é prioridade', '4.l.8 Não sei opinar sobre o uso de IA Generativa e LLMs na empresa', 'uso_ia_generativa_trabalho', 'ia_uso_pessoal_nenhuma', 'ia_uso_pessoal_gratuitas', 'ia_uso_pessoal_paga_propria', 'ia_uso_pessoal_empresa_paga', 'ia_uso_pessoal_copilot', 'objetivo_profissional', 'tipo_oportunidade_buscada', 'tempo_busca_emprego_meses', 'carreira_experiencia_processos_seletivos', 'rotina_engenheiro_dados', 'de_rotina_pipeline_codigo', 'de_rotina_etl_ferramentas', 'de_rotina_consultas_sql', 'de_rotina_integracao_plataformas', 'de_rotina_modelagem_arquitetura', 'de_rotina_manutencao_datalakes', 'de_rotina_modelagem_dados', 'de_rotina_qualidade_dados', 'de_rotina_nenhuma_das_opcoes', 'ferramentas_etl_engineer', 'de_etl_scripts_python', 'de_etl_sql_procedures', 'de_etl_airflow', 'de_etl_nifi', 'de_etl_luigi', 'de_etl_aws_glue', 'de_etl_talend', 'de_etl_pentaho', 'de_etl_alteryx', 'de_etl_stitch', 'de_etl_fivetran', 'de_etl_google_dataflow', 'de_etl_oracle_di', 'de_etl_ibm_datastage', 'de_etl_sap_bw', 'de_etl_ssis', 'de_etl_sas_di', 'de_etl_qlik_sense', 'de_etl_knime', 'de_etl_databricks', 'de_etl_nenhuma', 'de_empresa_possui_data_lake', 'de_empresa_tecnologia_data_lake', 'de_empresa_possui_data_warehouse', 'de_empresa_tecnologia_data_warehouse', 'de_ferramentas_qualidade_dados_lista', 'de_maior_tempo_gasto', 'de_maior_tempo_pipelines_codigo', 'de_maior_tempo_etl_ferramentas', 'de_maior_tempo_consultas_sql', 'de_maior_tempo_integracao_plataformas', 'de_maior_tempo_modelagem_arquitetura', 'de_maior_tempo_manutencao_datalakes', 'de_maior_tempo_modelagem_dados', 'de_maior_tempo_qualidade_dados', 'de_maior_tempo_nenhuma_das_opcoes', 'rotina_analista_dados', 'da_rotina_analise_codigo', 'da_rotina_dashboards_bi', 'da_rotina_consultas_sql', 'da_rotina_extracao_api', 'da_rotina_estatistica_testes', 'da_rotina_manutencao_etl', 'da_rotina_modelagem_dados', 'da_rotina_manutencao_planilhas', 'da_rotina_estatistica_avancada', 'da_rotina_nenhuma_das_opcoes', 'ferramentas_etl_analyst', 'da_etl_scripts_python', 'da_etl_sql_procedures', 'da_etl_airflow', 'da_etl_nifi', 'da_etl_luigi', 'da_etl_aws_glue', 'da_etl_talend', 'da_etl_pentaho', 'da_etl_alteryx', 'da_etl_stitch', 'da_etl_fivetran', 'da_etl_google_dataflow', 'da_etl_oracle_di', 'da_etl_ibm_datastage', 'da_etl_sap_bw', 'da_etl_ssis', 'da_etl_sas_di', 'da_etl_qlik_sense', 'da_etl_knime', 'da_etl_databricks', 'da_etl_nenhuma', 'da_ferramentas_autonomia_negocios_lista', 'da_autonomia_ferramentas_automl', 'da_autonomia_ferramentas_point_and_click', 'da_autonomia_ferramentas_product_insights', 'da_autonomia_ferramentas_crm_analytics', 'da_autonomia_ferramentas_nenhuma', 'da_autonomia_ferramentas_nao_sabe', 'da_maior_tempo_gasto', 'da_maior_tempo_analise_codigo', 'da_maior_tempo_dashboards_bi', 'da_maior_tempo_consultas_sql', 'da_maior_tempo_extracao_api', 'da_maior_tempo_estatistica_testes', 'da_maior_tempo_manutencao_etl', 'da_maior_tempo_modelagem_dados', 'da_maior_tempo_manutencao_planilhas', 'da_maior_tempo_estatistica_avancada', 'da_maior_tempo_nenhuma_das_opcoes', 'rotina_cientista_dados', 'ds_rotina_estudos_ad_hoc', 'ds_rotina_coleta_limpeza', 'ds_rotina_contato_negocios', 'ds_rotina_desenvolvimento_ml', 'ds_rotina_ml_em_producao', 'ds_rotina_manutencao_ml', 'ds_rotina_dashboards_bi', 'ds_rotina_estatistica_avancada', 'ds_rotina_manutencao_etl', 'ds_rotina_feature_store_mlops', 'ds_rotina_infraestrutura', 'ds_rotina_treino_llm', 'tecnicas_ml_cientista', 'ds_tecnica_regressao', 'ds_tecnica_classificacao_arvores_redes', 'ds_tecnica_sistemas_recomendacao', 'ds_tecnica_estatistica_bayesiana', 'ds_tecnica_nlp', 'ds_tecnica_estatistica_classica', 'ds_tecnica_markov_hmm', 'ds_tecnica_clusterizacao', 'ds_tecnica_series_temporais', 'ds_tecnica_reinforcement_learning', 'ds_tecnica_deteccao_fraude', 'ds_tecnica_visao_computacional', 'ds_tecnica_deteccao_churn', 'ds_tecnica_llm', 'tecnologias_cientista', 'ds_tecnologia_ferramentas_bi', 'ds_tecnologia_planilhas', 'ds_tecnologia_dev_local', 'ds_tecnologia_dev_nuvem', 'ds_tecnologia_automl', 'ds_tecnologia_etl', 'ds_tecnologia_plataformas_ml', 'ds_tecnologia_feature_store', 'ds_tecnologia_controle_versao', 'ds_tecnologia_data_apps', 'ds_tecnologia_estatistica_avancada', 'ds_maior_tempo_gasto', 'ds_maior_tempo_estudos_ad_hoc', 'ds_maior_tempo_coleta_limpeza', 'ds_maior_tempo_contato_negocios', 'ds_maior_tempo_desenvolvimento_ml', 'ds_maior_tempo_ml_em_producao', 'ds_maior_tempo_manutencao_ml', 'ds_maior_tempo_dashboards_bi', 'ds_maior_tempo_estatistica_avancada', 'ds_maior_tempo_manutencao_etl', 'ds_maior_tempo_feature_store_mlops', 'ds_maior_tempo_infraestrutura', 'ds_maior_tempo_treino_llm', 'salario_medio_mensal', 'grupo_cargo', 'experiencia_anos_num', 'usa_.net', 'usa_c_c++_c#', 'usa_java', 'usa_javascript', 'usa_julia', 'usa_matlab', 'usa_nenhuma', 'usa_não_utilizo_linguagem_de_programação_no_trabalho', 'usa_php', 'usa_python', 'usa_r', 'usa_rust', 'usa_sas_stata', 'usa_sql', 'usa_scala', 'usa_visual_basic_vba', 'ano', 'prejudicado_motivo_raca_etnia', 'prejudicado_motivo_genero', 'prejudicado_motivo_pcd', 'mudou_de_estado', 'insatisfacao_fator_falta_crescimento', 'insatisfacao_fator_salario_defasado', 'insatisfacao_fator_relacao_gestor', 'insatisfacao_fator_desejo_mudar_area', 'insatisfacao_fator_beneficios', 'insatisfacao_fator_ambiente_ruim', 'insatisfacao_fator_baixa_maturidade_empresa', 'fonte_dados_principal_relacionais', 'fonte_dados_principal_nosql', 'fonte_dados_principal_imagens', 'fonte_dados_principal_textos', 'fonte_dados_principal_videos', 'fonte_dados_principal_audios', 'fonte_dados_principal_planilhas', 'fonte_dados_principal_geo', 'cloud_preferida_lista', 'ia_uso_empresa_independente.1', 'ia_uso_empresa_centralizado.1', 'ia_uso_empresa_copilots.1', 'ia_uso_empresa_produtos_externos.1', 'ia_uso_empresa_produtos_internos.1', 'ia_uso_empresa_frente_negocio.1', 'ia_uso_empresa_nao_prioridade.1', 'ia_uso_empresa_nao_sabe.1', 'de_rotina_lista', 'de_ferramentas_etl_lista', 'da_rotina_lista', 'da_ferramentas_etl_lista', 'ds_rotina_lista', 'ds_tecnicas_lista', 'ds_tecnologias_lista', 'de_qualidade_great_expectations', 'de_qualidade_dbt', 'de_qualidade_aws_deequ', 'de_qualidade_apache_griffin', 'de_qualidade_datafold', 'de_qualidade_amundsen', 'de_qualidade_monte_carlo', 'de_qualidade_soda', 'de_qualidade_big_eye', 'de_qualidade_data_band', 'de_qualidade_anomalo', 'de_qualidade_metaplane', 'de_qualidade_acceldata', 'linguagem_principal_sql', 'linguagem_principal_r', 'linguagem_principal_python', 'linguagem_principal_c_cplusplus_csharp', 'linguagem_principal_dotnet', 'linguagem_principal_java', 'linguagem_principal_julia', 'linguagem_principal_sas_stata', 'linguagem_principal_vba', 'linguagem_principal_scala', 'linguagem_principal_matlab', 'linguagem_principal_php', 'linguagem_principal_javascript', 'linguagem_principal_nenhuma', 'de_qualidade_dados_great_expectations', 'de_qualidade_dados_dbt', 'de_qualidade_dados_aws_deequ', 'de_qualidade_dados_apache_griffin', 'de_qualidade_dados_datafold', 'de_qualidade_dados_amundsen', 'de_qualidade_dados_monte_carlo', 'de_qualidade_dados_soda', 'de_qualidade_dados_big_eye', 'de_qualidade_dados_data_band', 'de_qualidade_dados_anomalo', 'de_qualidade_dados_metaplane', 'de_qualidade_dados_acceldata', 'ds_tecnologia_nenhuma', 'dh_iniciativas_acessadas_lista', 'dh_iniciativa_blog', 'dh_iniciativa_podcast', 'dh_iniciativa_newsletter', 'dh_iniciativa_slack', 'dh_iniciativa_youtube', 'dh_iniciativa_nao_conhecia', 'usa_linguagem_net', 'usa_linguagem_c_c++_c#', 'usa_linguagem_java', 'usa_linguagem_javascript', 'usa_linguagem_julia', 'usa_linguagem_matlab', 'usa_linguagem_nenhuma', 'usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho', 'usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas', 'usa_linguagem_php', 'usa_linguagem_python', 'usa_linguagem_r', 'usa_linguagem_rust', 'usa_linguagem_sas_stata', 'usa_linguagem_sql', 'usa_linguagem_scala', 'usa_linguagem_visual_basic_vba', 'usa_bi_alteryx', 'usa_bi_metabase', 'usa_bi_powerbi', 'usa_bi_qlik', 'usa_bi_sap', 'usa_bi_superset', 'usa_bi_tableau', 'usa_bi_looker_studio', 'usa_bi_nenhuma', 'usa_bi_amazon_quicksight', 'usa_bi_ferramenta_propria', 'usa_bi_excel_gsheets', 'usa_bi_codigo_python_r', 'usa_bi_outras']
456

In [3]:
Path('dashboard_data').mkdir(exist_ok=True)
print("Pasta 'dashboard_data/' pronta para receber os arquivos de análise.")

Pasta 'dashboard_data/' pronta para receber os arquivos de análise.

In [4]:
df_final

,id_participante,data_envio,idade,faixa_idade,genero,etnia,pcd,experiencia_prejudicada,prejudicado_acredita_nao_ser_afetado,prejudicado_raca_etnia,...,usa_bi_sap,usa_bi_superset,usa_bi_tableau,usa_bi_looker_studio,usa_bi_nenhuma,usa_bi_amazon_quicksight,usa_bi_ferramenta_propria,usa_bi_excel_gsheets,usa_bi_codigo_python_r,usa_bi_outras
0,reb94rv0msth7q4nreb94riaq80iz3yi,2024-10-16 11:19:17,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,1,0,0
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,2024-10-16 20:45:31,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,2024-10-17 18:10:59,18.0,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,0,0,0,0,0,0,0,0,0,1
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,2024-10-22 18:03:00,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,2024-10-23 01:33:23,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17421,07nvo8cdy377a46gon207nvjebwe65zg,NaN,40.0,40-44,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0
17422,01mqnby32u01pg3nuj6vipp4mc06s8pg,NaN,27.0,25-29,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
17423,01fncs8qbhl9zx01fncs8rqib2zl3d18,NaN,24.0,22-24,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17424,075h3v2z19if04yn7o075h3vhifl38rw,NaN,38.0,35-39,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0
17425,037usz1h2yip96dgil4mhj037uszw1gk,NaN,27.0,25-29,Feminino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0

## 1 - TABELA DE EVOLUÇÃO SALARIAL POR CARGO

In [5]:
print(df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack())

grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [6]:
evolucao_salario_cargo = df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack()

In [7]:
print('Tabela gerada: ')
print(evolucao_salario_cargo)

Tabela gerada:
grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [8]:
evolucao_salario_cargo.to_csv(ANALISE_PARA_DASHBOARD/'04_analise_evolucao_salario_cargo.csv')
print(f'tabela evoluação salário por cargo criada e exportada para {ANALISE_PARA_DASHBOARD}')

tabela evoluação salário por cargo criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

## 2 - TABELA DE EVOLUÇÃO SALARIAL POR SENIORIDADE

In [9]:
evolucao_salario_senioridade = df_final.groupby(['ano', 'nivel_hierarquico'])['salario_medio_mensal'].mean().round(2).unstack()

In [10]:
evolucao_salario_senioridade

nivel_hierarquico   Júnior    Pleno    Sênior
ano
2021               3876.49  7609.92  12401.89
2022               3928.64  7961.82  12848.50
2023               3919.75  7533.55  13577.68
2024               4166.96  8048.79  14506.23

In [11]:
evolucao_salario_senioridade.reset_index().to_csv(ANALISE_PARA_DASHBOARD/'04_analise_evolucao_salario_senioridade.csv', index=False)
print(f'Tabela de evolução do salário médio por senioridade criada e exportada para {ANALISE_PARA_DASHBOARD}')

Tabela de evolução do salário médio por senioridade criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

##### Pergunta "4" das hipóteses respondidas ✅

## 3 - TABELA DE POPULARIDADE DE LINGUAGENS USADAS POR ANO

In [12]:
colunas_linguagens = [col for col in df_final.columns if col.startswith('usa_linguagem_')]

In [13]:
colunas_linguagens

['usa_linguagem_net',
 'usa_linguagem_c_c++_c#',
 'usa_linguagem_java',
 'usa_linguagem_javascript',
 'usa_linguagem_julia',
 'usa_linguagem_matlab',
 'usa_linguagem_nenhuma',
 'usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho',
 'usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas',
 'usa_linguagem_php',
 'usa_linguagem_python',
 'usa_linguagem_r',
 'usa_linguagem_rust',
 'usa_linguagem_sas_stata',
 'usa_linguagem_sql',
 'usa_linguagem_scala',
 'usa_linguagem_visual_basic_vba']

In [14]:
popularidade_linguagens = df_final.groupby('ano')[colunas_linguagens].sum()

In [15]:
popularidade_linguagens

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,42,64,84,174,8,15,788,0,162,38,1346,306,0,77,1487,89,160
2022,33,52,106,194,6,25,1290,0,319,39,2089,385,0,123,2367,119,218
2023,40,70,113,282,8,30,1521,0,305,56,2825,401,7,151,3156,131,285
2024,31,46,94,223,6,20,1628,165,0,34,2935,342,12,130,3146,126,215

In [16]:
##porcentagem
total_respondentes_ano = df_final['ano'].value_counts()
popularidade_linguagensa_pct = popularidade_linguagens.div(total_respondentes_ano, axis=0).mul(100).round(2)

In [17]:
popularidade_linguagensa_pct

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,1.59,2.42,3.18,6.58,0.30,0.57,29.79,0.00,6.12,1.44,50.89,11.57,0.00,2.91,56.22,3.36,6.05
2022,0.77,1.22,2.48,4.54,0.14,0.59,30.20,0.00,7.47,0.91,48.91,9.01,0.00,2.88,55.42,2.79,5.10
2023,0.76,1.32,2.13,5.33,0.15,0.57,28.74,0.00,5.76,1.06,53.37,7.58,0.13,2.85,59.63,2.47,5.38
2024,0.59,0.88,1.80,4.27,0.12,0.38,31.21,3.16,0.00,0.65,56.26,6.56,0.23,2.49,60.30,2.42,4.12

In [18]:
total_respondentes_ano

ano
2023    5293
2024    5217
2022    4271
2021    2645
Name: count, dtype: int64

In [19]:
popularidade_linguagensa_pct.to_csv(ANALISE_PARA_DASHBOARD/'08_analise_popularidade_linguagens_pct.csv')
print(f'Tabela gerada de % de uso da linguagem')

Tabela gerada de % de uso da linguagem

##### Pergunta número "8" das hipóteses respondida parte 1✅

## 4 - QUAL A EVOLUÇÃO DOS MODELOS DE TRABALHO (REMOTO, HÍBRIDO, PRESENCIAL)

In [20]:
print(df_final['modelo_trabalho_atual'].value_counts())

modelo_trabalho_atual
Modelo 100% remoto                                                                                                7447
Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente)    3378
Modelo 100% presencial                                                                                            2492
Modelo híbrido com dias fixos de trabalho presencial                                                              2358
Name: count, dtype: int64

In [21]:
df_final['modelo_trabalho_atual'].fillna('Não informado', inplace=True)

mapa_modelos = {
  "Modelo 100% remoto": "Remoto",
  "Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente)": "Híbrido Flexível",
  "Modelo 100% presencial":"Presencial",
  "Modelo híbrido com dias fixos de trabalho presencial": "Híbrido Fixo",
  "Não informado": "Não informado"
}

/tmp/ipykernel_14657/3910453653.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['modelo_trabalho_atual'].fillna('Não informado', inplace=True)

In [22]:
modelos_curtos = df_final['modelo_trabalho_atual'].replace(mapa_modelos)

In [23]:
df_final['modelo_trabalho_atual'].isna().sum()

np.int64(0)

In [24]:
pd.crosstab(df_final['ano'], df_final['modelo_trabalho_atual'], normalize='index').mul(100).round(2)

modelo_trabalho_atual,Modelo 100% presencial,Modelo 100% remoto,Modelo híbrido com dias fixos de trabalho presencial,Modelo híbrido flexível (o funcionário tem liberdade para escolher quando estar no escritório presencialmente),Não informado
ano,,,,,
2021,12.40,50.47,9.11,17.43,10.59
2022,13.63,39.55,11.17,22.15,13.51
2023,14.93,41.58,14.93,18.36,10.20
2024,15.18,42.59,16.29,19.15,6.79

In [25]:
df_final['modelo_trabalho_limpo'] = df_final['modelo_trabalho_atual'].replace(mapa_modelos)

In [26]:
evolucao_modelo_trabalho_pct = pd.crosstab(df_final['ano'], df_final['modelo_trabalho_limpo'], normalize='index').mul(100).round(2)

In [27]:
evolucao_modelo_trabalho_pct

modelo_trabalho_limpo,Híbrido Fixo,Híbrido Flexível,Não informado,Presencial,Remoto
ano,,,,,
2021,9.11,17.43,10.59,12.40,50.47
2022,11.17,22.15,13.51,13.63,39.55
2023,14.93,18.36,10.20,14.93,41.58
2024,16.29,19.15,6.79,15.18,42.59

In [28]:
evolucao_modelo_trabalho_pct.to_csv(ANALISE_PARA_DASHBOARD/'18_analise_evolucao_modelo_trabalho_pct.csv')

##### Hipótese "18" respondida ✅

## 5 EXISTE DIFERENÇA SALARIAL POR GÊNERO (GENDER PAY GAP)?

In [29]:
print('valores coluna gênero')
print(df_final['genero'].value_counts())

valores coluna gênero
genero
Masculino               13281
Feminino                 4068
Prefiro não informar       43
Outro                      25
Name: count, dtype: int64

In [30]:
analise_genero_senioridade = df_final.groupby(['ano', 'nivel_hierarquico', 'genero'])['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [31]:
analise_genero_senioridade.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [32]:
analise_genero_senioridade[['salario_medio', 'salario_mediana']] = analise_genero_senioridade[['salario_medio', 'salario_mediana']].round(2)

In [33]:
print("\nTabela gerada (Estatísticas Salariais por Ano e Gênero):")
print(analise_genero_senioridade.unstack(level='genero'))

Tabela gerada (Estatísticas Salariais por Ano e Gênero):
                       salario_medio                                           \
genero                      Feminino Masculino     Outro Prefiro não informar
ano  nivel_hierarquico
2021 Júnior                  4149.79   3793.73   3833.83                  NaN
     Pleno                   7492.87   7591.93  20000.50                  NaN
     Sênior                 10612.20  12749.48       NaN                  NaN
2022 Júnior                  3972.92   3926.46       NaN              3000.38
     Pleno                   7681.86   8069.58       NaN              7625.50
     Sênior                 11168.95  13288.24       NaN             10000.50
2023 Júnior                  3706.17   4001.23   1500.50              5833.83
     Pleno                   7464.89   7564.01   6125.50              6750.50
     Sênior                 12355.56  13863.08   8500.50             31000.62
2024 Júnior                  4161.64   4118.46       NaN             14667.33
     Pleno                   7817.44   8135.19   7000.50              8000.50
     Sênior                 12513.94  15059.10   9000.50             15250.58

                       salario_mediana                     \
genero                        Feminino Masculino    Outro
ano  nivel_hierarquico
2021 Júnior                     3500.5    3500.5   5000.5
     Pleno                      7000.5    7000.5  20000.5
     Sênior                    10000.5   10000.5      NaN
2022 Júnior                     3500.5    3500.5      NaN
     Pleno                      7000.5    7000.5      NaN
     Sênior                    10000.5   10000.5      NaN
2023 Júnior                     3500.5    3500.5   1500.5
     Pleno                      7000.5    7000.5   6000.5
     Sênior                    10000.5   14000.5   8500.5
2024 Júnior                     3500.5    3500.5      NaN
     Pleno                      7000.5    7000.5   7000.5
     Sênior                    10000.5   14000.5  10000.5

                                            contagem                  \
genero                 Prefiro não informar Feminino Masculino Outro
ano  nivel_hierarquico
2021 Júnior                             NaN    144.0     474.0   3.0
     Pleno                              NaN    131.0     525.0   2.0
     Sênior                             NaN     94.0     484.0   NaN
2022 Júnior                          2000.5    272.0     743.0   NaN
     Pleno                           8500.5    295.0     760.0   NaN
     Sênior                         10000.5    187.0     709.0   NaN
2023 Júnior                          7000.5    299.0     743.0   1.0
     Pleno                           6000.5    337.0    1047.0   4.0
     Sênior                         35000.5    307.0    1106.0   2.0
2024 Júnior                          2500.5    242.0     623.0   NaN
     Pleno                           7000.5    366.0    1006.0   2.0
     Sênior                         10000.5    335.0    1229.0   3.0


genero                 Prefiro não informar
ano  nivel_hierarquico
2021 Júnior                             NaN
     Pleno                              NaN
     Sênior                             NaN
2022 Júnior                             4.0
     Pleno                              4.0
     Sênior                             1.0
2023 Júnior                             3.0
     Pleno                              4.0
     Sênior                             4.0
2024 Júnior                             3.0
     Pleno                              3.0
     Sênior                             6.0

In [34]:
media_pivot_senioridade = analise_genero_senioridade['salario_medio'].unstack(level='genero')

In [35]:
if 'Masculino' in media_pivot_senioridade.columns and 'Feminino' in media_pivot_senioridade.columns:
  media_pivot_senioridade['pay_gap_percentual'] = \
    ((media_pivot_senioridade['Masculino'] - media_pivot_senioridade['Feminino']) / media_pivot_senioridade['Masculino']) * 100
  
  pay_gap_por_nivel = media_pivot_senioridade[['Masculino', 'Feminino', 'pay_gap_percentual']].round(2)

  print("\nTabela Pay Gap por Nível (Diferença % entre Salário Médio Masculino e Feminino):")
  print(pay_gap_por_nivel)

else:
  print("\nNão foi possível calcular o Pay Gap por nível (colunas 'Masculino' ou 'Feminino' não encontradas).")

Tabela Pay Gap por Nível (Diferença % entre Salário Médio Masculino e Feminino):
genero                  Masculino  Feminino  pay_gap_percentual
ano  nivel_hierarquico
2021 Júnior               3793.73   4149.79               -9.39
     Pleno                7591.93   7492.87                1.30
     Sênior              12749.48  10612.20               16.76
2022 Júnior               3926.46   3972.92               -1.18
     Pleno                8069.58   7681.86                4.80
     Sênior              13288.24  11168.95               15.95
2023 Júnior               4001.23   3706.17                7.37
     Pleno                7564.01   7464.89                1.31
     Sênior              13863.08  12355.56               10.87
2024 Júnior               4118.46   4161.64               -1.05
     Pleno                8135.19   7817.44                3.91
     Sênior              15059.10  12513.94               16.90

In [36]:
analise_genero_senioridade.to_csv(ANALISE_PARA_DASHBOARD/'05_analise_salario_por_genero_senioridade_stats.csv')
print(f"\n>> Tabela detalhada por gênero e senioridade salva em {ANALISE_PARA_DASHBOARD}")

>> Tabela detalhada por gênero e senioridade salva em /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

In [37]:
if 'pay_gap_por_nivel' in locals(): 
  # Resetamos o índice para que 'ano' e 'nivel_hierarquico' virem colunas
  pay_gap_por_nivel.to_csv(ANALISE_PARA_DASHBOARD/'05_analise_pay_gap_percentual_por_nivel.csv')
  print(f">> Tabela do Pay Gap percentual por nível salva em {ANALISE_PARA_DASHBOARD}'/analise_pay_gap_percentual_por_nivel.csv'\n")

>> Tabela do Pay Gap percentual por nível salva em /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data'/analise_pay_gap_percentual_por_nivel.csv'

##### Hipótese 5 respondida ✅

## 6 - QUAL A RELAÇÃO ENTRE NÍVEL DE ENSINO E SALÁRIO?

In [38]:
df_final['nivel_ensino'].value_counts()

nivel_ensino
Graduação/Bacharelado         5929
Pós-graduação                 5898
Estudante de Graduação        2270
Mestrado                      2203
Doutorado ou Phd               733
Não tenho graduação formal     362
Prefiro não informar            31
Name: count, dtype: int64

In [39]:
ordem_ensino = [
  'Não tenho graduação formal',
  'Estudante de Graduação',
  'Graduação/Bacharelado',
  'Pós-graduação',
  'Mestrado',
  'Doutorado ou Phd',
  'Prefiro não informar'
]

In [40]:
df_final['nivel_ensino_cat'] = pd.Categorical(
    df_final['nivel_ensino'],
    categories=ordem_ensino,
    ordered=True
)

In [41]:
analise_ensino = df_final.groupby(['ano', 'nivel_ensino_cat'], observed=True)['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [42]:
analise_ensino.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [43]:
analise_ensino.columns

Index(['salario_medio', 'salario_mediana', 'contagem'], dtype='object')

In [44]:
analise_ensino[['salario_medio', 'salario_mediana']] = analise_ensino[['salario_medio', 'salario_mediana']].round(2)

In [45]:
print("\nTabela gerada (Estatísticas Salariais por Ano e Nível de Ensino):")
print(analise_ensino.unstack(level='ano'))

Tabela gerada (Estatísticas Salariais por Ano e Nível de Ensino):
                           salario_medio                                \
ano                                 2021      2022      2023      2024
nivel_ensino_cat
Não tenho graduação formal      10118.16   7756.43   8843.88   9032.95
Estudante de Graduação           3963.68   4108.39   4471.45   4736.26
Graduação/Bacharelado            8387.85   8706.45   9187.58  10538.52
Pós-graduação                   10504.36  11125.60  11787.40  13419.06
Mestrado                        13204.10  13943.70  14083.85  16108.59
Doutorado ou Phd                12701.55  13873.80  14766.82  15115.10
Prefiro não informar             6333.83   2889.33  10250.42  16500.50

                           salario_mediana                             \
ano                                   2021     2022     2023     2024
nivel_ensino_cat
Não tenho graduação formal          7000.5   5000.5   5000.5   7000.5
Estudante de Graduação              2500.5   3500.5   3500.5   3500.5
Graduação/Bacharelado               7000.5   7000.5   7000.5  10000.5
Pós-graduação                      10000.5  10000.5  10000.5  10000.5
Mestrado                           10000.5  10000.5  10000.5  14000.5
Doutorado ou Phd                   10000.5  10000.5  14000.5  14000.5
Prefiro não informar                2500.5   2500.5   7500.5  12500.5

                           contagem
ano                            2021  2022  2023  2024
nivel_ensino_cat
Não tenho graduação formal       51    84    83    77
Estudante de Graduação          299   468   532   492
Graduação/Bacharelado           830  1328  1641  1618
Pós-graduação                   778  1219  1701  1860
Mestrado                        307   440   606   620
Doutorado ou Phd                 97   146   184   192
Prefiro não informar              3     9     6     4

In [46]:
analise_ensino.to_csv(ANALISE_PARA_DASHBOARD/'15_analise_salario_por_nivel_ensino_stats.csv')

In [47]:
analise_ensino_senioridade = df_final.groupby(['ano', 'nivel_hierarquico', 'nivel_ensino_cat'], observed=True)['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [48]:
analise_ensino_senioridade.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [49]:
analise_ensino_senioridade[['salario_medio', 'salario_mediana']] = analise_ensino_senioridade[['salario_medio', 'salario_mediana']].round(2)

In [50]:
print("\nTabela gerada (Estatísticas Salariais por Ano, Senioridade e Nível de Ensino):")
print()
try:
    print(analise_ensino_senioridade.unstack(level='ano')) # Exibe dados de Sênior em 2024
except KeyError:
    print("Não há dados para Sênior em 2024 ou a estrutura do índice está diferente.")

Tabela gerada (Estatísticas Salariais por Ano, Senioridade e Nível de Ensino):

                                             salario_medio            \
ano                                                   2021      2022
nivel_hierarquico nivel_ensino_cat
Júnior            Não tenho graduação formal       3821.89   2894.35
                  Estudante de Graduação           2654.12   2820.98
                  Graduação/Bacharelado            4161.43   4253.45
                  Pós-graduação                    4929.07   4896.33
                  Mestrado                         4750.50   4672.38
                  Doutorado ou Phd                 6188.00   5972.72
                  Prefiro não informar             2500.50   3000.50
Pleno             Não tenho graduação formal       6556.06   7705.07
                  Estudante de Graduação           5658.82   5435.28
                  Graduação/Bacharelado            7492.00   7847.29
                  Pós-graduação                    7378.67   7861.61
                  Mestrado                         9799.21  10295.78
                  Doutorado ou Phd                 9429.07   9100.50
                  Prefiro não informar                 NaN   3333.83
Sênior            Não tenho graduação formal      18115.92  14400.55
                  Estudante de Graduação          10767.17   8929.07
                  Graduação/Bacharelado           11303.63  12829.94
                  Pós-graduação                   11523.15  12068.69
                  Mestrado                        15553.72  15430.96
                  Doutorado ou Phd                14433.83  15675.96
                  Prefiro não informar            14000.50   1000.00

                                                                  \
ano                                               2023      2024
nivel_hierarquico nivel_ensino_cat
Júnior            Não tenho graduação formal   2283.07   3500.43
                  Estudante de Graduação       2784.59   2850.97
                  Graduação/Bacharelado        4325.91   4478.82
                  Pós-graduação                4690.15   5143.83
                  Mestrado                     5000.49   6270.77
                  Doutorado ou Phd             4800.47   8500.45
                  Prefiro não informar         5000.50  40001.00
Pleno             Não tenho graduação formal   6704.20   7269.71
                  Estudante de Graduação       5935.61   6667.17
                  Graduação/Bacharelado        7396.66   7847.57
                  Pós-graduação                7651.85   8090.82
                  Mestrado                     8648.76   9816.96
                  Doutorado ou Phd             9232.21   8392.65
                  Prefiro não informar         5500.25   4000.25
Sênior            Não tenho graduação formal  14583.86  13100.50
                  Estudante de Graduação      10878.55  10271.93
                  Graduação/Bacharelado       13365.56  14396.78
                  Pós-graduação               13007.84  14004.74
                  Mestrado                    15484.30  16206.27
                  Doutorado ou Phd            15199.23  16309.51
                  Prefiro não informar             NaN  18000.50

                                             salario_mediana           \
ano                                                     2021     2022
nivel_hierarquico nivel_ensino_cat
Júnior            Não tenho graduação formal          3500.5   2500.5
                  Estudante de Graduação              2500.5   2500.5
                  Graduação/Bacharelado               3500.5   3500.5
                  Pós-graduação                       3500.5   5000.5
                  Mestrado                            5000.5   4250.5
                  Doutorado ou Phd                    5000.5   5000.5
                  Prefiro não informar                2500.5   2500.5
Pleno             Não tenho graduação formal          5000.5   7000.5
                  Estudante de Graduação              5000.5   5000.5
                  Graduação/Bacharelado               7000.5   7000.5
                  Pós-graduação                       7000.5   7000.5
                  Mestrado                            7000.5  10000.5
                  Doutorado ou Phd                    7000.5  10000.5
                  Prefiro não informar                   NaN   3500.5
Sênior            Não tenho graduação formal         14000.5  12000.5
                  Estudante de Graduação             10000.5  10000.5
                  Graduação/Bacharelado              10000.5  10000.5
                  Pós-graduação                      10000.5  10000.5
                  Mestrado                           14000.5  14000.5
                  Doutorado ou Phd                   14000.5  14000.5
                  Prefiro não informar               14000.5   1000.0

                                                                 contagem  \
ano                                               2023      2024     2021
nivel_hierarquico nivel_ensino_cat
Júnior            Não tenho graduação formal   2500.50   2500.50     14.0
                  Estudante de Graduação       2500.50   2500.50    205.0
                  Graduação/Bacharelado        3500.50   5000.50    233.0
                  Pós-graduação                5000.50   5000.50    105.0
                  Mestrado                     5000.50   5000.50     46.0
                  Doutorado ou Phd             5000.50   5000.50     16.0
                  Prefiro não informar         5000.50  40001.00      2.0
Pleno             Não tenho graduação formal   5000.50   7000.50      9.0
                  Estudante de Graduação       5000.50   5000.50     60.0
                  Graduação/Bacharelado        7000.50   7000.50    294.0
                  Pós-graduação                7000.50   7000.50    197.0
                  Mestrado                    10000.50  10000.50     77.0
                  Doutorado ou Phd            10000.50  10000.50     21.0
                  Prefiro não informar         5500.25   4000.25      NaN
Sênior            Não tenho graduação formal  14000.50  10000.50     13.0
                  Estudante de Graduação      10000.50  10000.50     15.0
                  Graduação/Bacharelado       10000.50  14000.50    160.0
                  Pós-graduação               10000.50  14000.50    265.0
                  Mestrado                    14000.50  14000.50     94.0
                  Doutorado ou Phd            14000.50  14000.50     30.0
                  Prefiro não informar             NaN  18000.50      1.0


ano                                            2022   2023   2024
nivel_hierarquico nivel_ensino_cat
Júnior            Não tenho graduação formal   33.0   23.0   23.0
                  Estudante de Graduação      312.0  324.0  301.0
                  Graduação/Bacharelado       423.0  421.0  346.0
                  Pós-graduação               168.0  203.0  150.0
                  Mestrado                     64.0   58.0   37.0
                  Doutorado ou Phd             18.0   15.0   10.0
                  Prefiro não informar          5.0    2.0    1.0
Pleno             Não tenho graduação formal   22.0   27.0   26.0
                  Estudante de Graduação       92.0  131.0  129.0
                  Graduação/Bacharelado       421.0  573.0  546.0
                  Pós-graduação               360.0  446.0  465.0
                  Mestrado                    127.0  172.0  158.0
                  Doutorado ou Phd             35.0   41.0   51.0
                  Prefiro não informar          3.0    2.0    2.0
Sênior            Não tenho graduação formal   10.0   18.0   15.0
                  Estudante de Graduação       42.0   41.0   35.0
                  Graduação/Bacharelado       299.0  452.0  482.0
                  Pós-graduação               374.0  614.0  708.0
                  Mestrado                    115.0  216.0  243.0
                  Doutorado ou Phd             57.0   78.0   89.0
                  Prefiro não informar          1.0    NaN    1.0

In [51]:
analise_ensino_senioridade.to_csv(ANALISE_PARA_DASHBOARD/'15_analise_salario_por_ensino_senioridade_stats.csv')

##### Hipótese 15 respondida ✅

## 7 - HÁ DIFERENÇAS REGIONAIS DE SALÁRIO ?

In [52]:
print(df_final['regiao_residencia'].value_counts())
print(df_final['regiao_residencia'].isna().sum())

regiao_residencia
Sudeste         10618
Sul              3061
Nordeste         1987
Centro-oeste     1082
Norte             259
Exterior           53
Name: count, dtype: int64
366

In [53]:
df_final['regiao_residencia'].fillna('Não informado', inplace=True)

/tmp/ipykernel_14657/2542900621.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['regiao_residencia'].fillna('Não informado', inplace=True)

In [54]:
df_final['regiao_residencia'].value_counts()

regiao_residencia
Sudeste          10618
Sul               3061
Nordeste          1987
Centro-oeste      1082
Não informado      366
Norte              259
Exterior            53
Name: count, dtype: int64

In [55]:
analise_regiao_salario = df_final.groupby(['ano','regiao_residencia'])['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [56]:
analise_regiao_salario.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [57]:
analise_regiao_salario[['salario_medio', 'salario_mediana']] = analise_regiao_salario[['salario_medio', 'salario_mediana']].round(2)

In [58]:
print("\nTabela gerada (Estatísticas Salariais por Ano e Região):")
# Usamos unstack no ano para comparar regiões lado a lado
print(analise_regiao_salario.unstack(level='ano'))

Tabela gerada (Estatísticas Salariais por Ano e Região):
                  salario_medio                               salario_mediana  \
ano                        2021      2022      2023      2024            2021
regiao_residencia
Centro-oeste           10145.84   8876.81  10299.84  10175.49         10000.5
Exterior               19366.43       NaN       NaN       NaN         14000.5
Nordeste                7225.48   7462.67   8025.45   9664.93          5000.5
Norte                   7519.69   7121.46   7891.79   8719.79          5000.5
Não informado               NaN  17730.81  18762.67  21608.25             NaN
Sudeste                 9563.70  10200.97  10907.44  12599.66          7000.5
Sul                     8567.26   8932.84   9483.01  10384.22          7000.5

                                             contagem
ano                   2022     2023     2024     2021    2022    2023    2024
regiao_residencia
Centro-oeste        7000.5  10000.5   7000.5    172.0   190.0   304.0   300.0
Exterior               NaN      NaN      NaN     41.0     NaN     NaN     NaN
Nordeste            5000.5   7000.5   7000.5    240.0   423.0   501.0   447.0
Norte               5000.5   7000.5   7000.5     26.0    62.0    69.0    57.0
Não informado      14000.5  18000.5  22500.5      NaN    76.0   103.0   130.0
Sudeste            10000.5  10000.5  10000.5   1519.0  2337.0  2890.0  2940.0
Sul                 7000.5   7000.5  10000.5    367.0   606.0   886.0   989.0

In [59]:
analise_regiao_salario.to_csv(ANALISE_PARA_DASHBOARD/'07_analise_salario_por_regiao_stats.csv')

In [60]:
analise_regiao_senioridade = df_final.groupby(['ano', 'regiao_residencia', 'nivel_hierarquico'])['salario_medio_mensal'].agg(['mean', 'median', 'count'])

In [61]:
analise_regiao_senioridade.columns = ['salario_medio', 'salario_mediana', 'contagem']

In [62]:
analise_regiao_senioridade[['salario_medio', 'salario_mediana']] = analise_regiao_senioridade[['salario_medio', 'salario_mediana']].round(2)

In [63]:
print("\n--- Aprofundamento: Salário por Região e Senioridade ---")
print(analise_regiao_senioridade.unstack(level='nivel_hierarquico'))

--- Aprofundamento: Salário por Região e Senioridade ---
                       salario_medio                     salario_mediana  \
nivel_hierarquico             Júnior     Pleno    Sênior          Júnior
ano  regiao_residencia
2021 Centro-oeste            4571.90   8451.72  13392.17          3500.5
     Exterior                6278.28  16591.41  27107.75          5000.5
     Nordeste                3518.53   7058.47   9930.73          3500.5
     Norte                   4333.75   4955.00   6500.50          3000.5
     Sudeste                 3742.09   7644.59  11977.96          3500.5
     Sul                     4176.02   6942.17  12630.14          3500.5
2022 Centro-oeste            4031.72   8182.32  13854.16          3000.5
     Nordeste                3600.48   7218.99  11563.80          2500.5
     Norte                   3364.09   8222.75  11500.50          3500.5
     Não informado          11750.50  15357.66  22577.52          6000.5
     Sudeste                 3970.31   7755.52  12734.33          3500.5
     Sul                     3733.41   7951.28  12046.61          3500.5
2023 Centro-oeste            4099.18   7994.25  14242.26          3500.5
     Nordeste                3443.74   6676.09  13405.48          3500.5
     Norte                   4571.88   6222.72  12150.50          5000.5
     Não informado           6625.45  15708.83  23364.23          6000.5
     Sudeste                 3899.73   7572.99  13323.48          3500.5
     Sul                     3907.05   7234.77  13124.09          3500.5
2024 Centro-oeste            4500.47   7082.02  14532.96          2500.5
     Nordeste                3641.98   7344.46  14551.70          2500.5
     Norte                   3250.47   7600.50  14711.03          2500.5
     Não informado          11867.20  18371.47  23235.26         10000.5
     Sudeste                 4111.60   8109.93  14552.32          3500.5
     Sul                     3934.91   7475.75  13065.98          3500.5

                                         contagem
nivel_hierarquico         Pleno   Sênior   Júnior Pleno Sênior
ano  regiao_residencia
2021 Centro-oeste        7000.5  14000.5       42    41     60
     Exterior           18000.5  35000.5        9    11     14
     Nordeste            7000.5  10000.5       83    69     43
     Norte               5000.5   7000.5        6    11      3
     Sudeste             7000.5  10000.5      387   406    377
     Sul                 7000.5  10000.5       94   120     81
2022 Centro-oeste        7000.5  14000.5       64    55     41
     Nordeste            7000.5  10000.5      155   119     79
     Norte               7000.5  10000.5       22    18      8
     Não informado      10000.5  18000.5        8    28     26
     Sudeste             7000.5  10000.5      613   647    603
     Sul                 7000.5  10000.5      161   193    141
2023 Centro-oeste        7000.5  14000.5       76    80     91
     Nordeste            7000.5  14000.5      141   168    121
     Norte               7000.5  10000.5       21    27     10
     Não informado      14000.5  22500.5       20    24     33
     Sudeste             7000.5  10000.5      590   807    901
     Sul                 7000.5  10000.5      198   286    263
2024 Centro-oeste        7000.5  14000.5       71    92     77
     Nordeste            7000.5  14000.5      106   141    127
     Norte               7000.5  14000.5       16    15     19
     Não informado      18000.5  22500.5       15    31     49
     Sudeste             7000.5  14000.5      477   795    965
     Sul                 7000.5  10000.5      183   303    336

In [64]:
analise_regiao_senioridade.to_csv(ANALISE_PARA_DASHBOARD/'07_analise_salario_por_regiao_senioridade.csv')

##### Hipótese 7 respondida ✅

## 8 - QUAIS AS FERRAMENTAS DE BI MAIS POPULARES POR ANO ?

In [65]:
print("--- Gerando Análise 7: Popularidade das Ferramentas de BI ---")
colunas_bi = sorted([col for col in df_final.columns if col.startswith('usa_bi_')])

--- Gerando Análise 7: Popularidade das Ferramentas de BI ---

In [66]:
print(colunas_bi)
print(len(colunas_bi))

['usa_bi_alteryx', 'usa_bi_amazon_quicksight', 'usa_bi_codigo_python_r', 'usa_bi_excel_gsheets', 'usa_bi_ferramenta_propria', 'usa_bi_looker_studio', 'usa_bi_metabase', 'usa_bi_nenhuma', 'usa_bi_outras', 'usa_bi_powerbi', 'usa_bi_qlik', 'usa_bi_sap', 'usa_bi_superset', 'usa_bi_tableau']
14

In [67]:
popularidade_bi = df_final.groupby('ano')[colunas_bi].sum()
total_respondentes_ano = df_final['ano'].value_counts()
popularidade_bi_pct = popularidade_bi.div(total_respondentes_ano, axis=0).mul(100).round(2)

In [68]:
popularidade_bi_pct

,usa_bi_alteryx,usa_bi_amazon_quicksight,usa_bi_codigo_python_r,usa_bi_excel_gsheets,usa_bi_ferramenta_propria,usa_bi_looker_studio,usa_bi_metabase,usa_bi_nenhuma,usa_bi_outras,usa_bi_powerbi,usa_bi_qlik,usa_bi_sap,usa_bi_superset,usa_bi_tableau
ano,,,,,,,,,,,,,,
2021,1.97,1.63,0.76,8.43,0.11,15.65,7.83,38.60,15.39,36.82,4.46,1.55,0.87,12.67
2022,0.16,0.05,0.02,0.44,0.00,1.24,0.61,95.88,0.96,2.27,0.19,0.05,0.09,0.82
2023,1.89,2.61,0.00,7.39,0.00,16.97,6.12,36.46,16.40,40.70,3.67,1.51,1.61,13.47
2024,1.38,3.22,0.00,7.38,0.00,15.93,6.10,37.40,16.04,38.26,3.41,1.05,1.86,13.17

In [69]:
nomes_limpos_bi = {col: col.replace('usa_bi_', '').replace('_', ' ').title() for col in popularidade_bi_pct.columns}
popularidade_bi_pct.rename(columns=nomes_limpos_bi, inplace=True)

In [70]:
nomes_limpos_bi

{'usa_bi_alteryx': 'Alteryx',
 'usa_bi_amazon_quicksight': 'Amazon Quicksight',
 'usa_bi_codigo_python_r': 'Codigo Python R',
 'usa_bi_excel_gsheets': 'Excel Gsheets',
 'usa_bi_ferramenta_propria': 'Ferramenta Propria',
 'usa_bi_looker_studio': 'Looker Studio',
 'usa_bi_metabase': 'Metabase',
 'usa_bi_nenhuma': 'Nenhuma',
 'usa_bi_outras': 'Outras',
 'usa_bi_powerbi': 'Powerbi',
 'usa_bi_qlik': 'Qlik',
 'usa_bi_sap': 'Sap',
 'usa_bi_superset': 'Superset',
 'usa_bi_tableau': 'Tableau'}

In [71]:
print(f"Tabela gerada (% de usuários por ferramenta de BI):")
print(popularidade_bi_pct)

Tabela gerada (% de usuários por ferramenta de BI):
      Alteryx  Amazon Quicksight  Codigo Python R  Excel Gsheets  \
ano
2021     1.97               1.63             0.76           8.43
2022     0.16               0.05             0.02           0.44
2023     1.89               2.61             0.00           7.39
2024     1.38               3.22             0.00           7.38

      Ferramenta Propria  Looker Studio  Metabase  Nenhuma  Outras  Powerbi  \
ano
2021                0.11          15.65      7.83    38.60   15.39    36.82
2022                0.00           1.24      0.61    95.88    0.96     2.27
2023                0.00          16.97      6.12    36.46   16.40    40.70
2024                0.00          15.93      6.10    37.40   16.04    38.26

      Qlik   Sap  Superset  Tableau
ano
2021  4.46  1.55      0.87    12.67
2022  0.19  0.05      0.09     0.82
2023  3.67  1.51      1.61    13.47
2024  3.41  1.05      1.86    13.17

In [72]:
popularidade_bi_pct.to_csv(ANALISE_PARA_DASHBOARD/'08_analise_popularidade_bi_pct.csv')

##### Hipótese 8 respondida part 2 ✅

## 9 - Qual a popularidade das plataformas Cloud por ano?

In [73]:
print(df_final['clouds_utilizadas'].unique().tolist())

['Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft)', 'Google Cloud (GCP)', 'Amazon Web Services (AWS)', nan, 'IBM', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Cloud Própria', 'Oracle Cloud, Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud', 'Google Cloud (GCP), Digital Ocean', 'Oracle Cloud', 'Amazon Web Services (AWS), Cloud Própria, Oracle Cloud', 'Servidores On Premise/Não utilizamos Cloud, Cloud Própria', 'Google Cloud (GCP), nenhuma', 'Amazon Web Services (AWS), Google Cloud (GCP)', 'Azure (Microsoft), IBM, Cloud Própria', 'IBM, Azure (Microsoft)', 'Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Oracle Cloud', 'Google Cloud (GCP), Amazon Web Services (AWS), Azure (Microsoft)', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud', 'Cloud Própria, Oracle Cloud', 'Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Amazon Web Services (AWS)', 'Não utilizado Cloud', 'Azure (Microsoft), hdfs, impala', 'Google Drive', 'Google Cloud (GCP), Azure (Microsoft)', 'Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP)', 'Não utilizo', 'Não usamos cloud', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'Azure (Microsoft), Amazon Web Services (AWS), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Cloud Própria, Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'Google Cloud (GCP), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP)', 'Nenhuma', 'Não usamos', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Oracle Cloud', 'Amazon Web Services (AWS), Cloud Própria', 'Google Cloud (GCP), Oracle Cloud', 'Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', 'Azure (Microsoft), IBM', 'Amazon Web Services (AWS), Databricks', 'Amazon Web Services (AWS), Google Cloud (GCP), Azure (Microsoft)', 'Azure (Microsoft), Oracle Cloud, Amazon Web Services (AWS)', 'Azure (Microsoft), Huawei', 'Amazon Web Services (AWS), Azure (Microsoft)', 'Cloud Própria, Azure (Microsoft)', 'Google Cloud (GCP), Magalu Cloud', 'TOTVS', 'Azure (Microsoft), Amazon Web Services (AWS), IBM, Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Heroku', 'Azure (Microsoft), Google Cloud (GCP)', 'Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Cloud Própria', 'A empresa usa Oracle cloud, mas eu não tenho acesso ainda', 'Google Cloud (GCP), Azure (Microsoft), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Cloudera', 'Qlik sense', 'Não Utilizo', 'Amazon Web Services (AWS), Azure (Microsoft), Oracle Cloud', 'Cloud Própria, IBM, Azure (Microsoft)', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', 'Protheus', 'Google Cloud (GCP), Oracle Cloud, Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Sharepoint', 'Azure (Microsoft), Cloud Própria, Amazon Web Services (AWS)', 'Google Cloud (GCP), Azure (Microsoft), Oracle Cloud', 'Google Cloud (GCP), Cloud Própria', 'Google Cloud (GCP), Databricks', 'Azure (Microsoft), IBM, Google Cloud (GCP), Amazon Web Services (AWS)', 'Oracle Cloud, Cloud Própria', 'Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'nenhum', 'IBM, Azure (Microsoft), Google Cloud (GCP)', 'sharepoint', 'Azure (Microsoft), Cloud Própria', 'Google Cloud (GCP), IBM, Amazon Web Services (AWS), Cloud Própria', 'Azure (Microsoft), Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Openshift', 'Cloud Própria, Amazon Web Services (AWS)', 'Databricks', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP), Azure (Microsoft)', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), IBM, Google Cloud (GCP), Azure (Microsoft)', 'não uso', 'Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud', 'Qlik', 'Digital ocean', 'Azure (Microsoft), Amazon Web Services (AWS), Google Cloud (GCP)', 'Azure (Microsoft), IBM, Amazon Web Services (AWS)', 'Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Azure (Microsoft), IBM, Cloud Própria', 'Oracle Cloud, Amazon Web Services (AWS), Azure (Microsoft), Cloud Própria', 'Servidores On Premise/Não utilizamos Cloud, IBM', 'HPCC System', 'Não utilizo.', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, IBM', 'ArcGIS Online', 'Google Cloud (GCP), Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Google Cloud (GCP), Oracle Cloud', 'Eu especificamente não uso cloud, mas a empresa azure', 'Nenhum', 'Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP)', 'SharePoint', 'Cloud Própria, Google Cloud (GCP)', 'Oracle Cloud, Azure (Microsoft)', 'Google Cloud (GCP), IBM', 'Cloud Própria, Amazon Web Services (AWS), Azure (Microsoft), Oracle Cloud', 'Não sei', 'Oracle Cloud, IBM, Cloudera', 'Oracle Cloud, Google Cloud (GCP)', 'Amazon Web Services (AWS), Google Cloud (GCP), Azure (Microsoft), Cloud Própria', 'IBM, Amazon Web Services (AWS)', 'Amazon Web Services (AWS), IBM', 'Azure (Microsoft), Nao', 'Azure (Microsoft), Oracle Cloud, Cloud Própria', 'Huawei Cloud', 'Amazon Web Services (AWS), Oracle Cloud, Azure (Microsoft)', 'Amazon Web Services (AWS), Google Cloud (GCP), Cloud Própria, Azure (Microsoft)', 'IBM, Cloud Própria', 'Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'Azure (Microsoft), Oracle Cloud, Google Cloud (GCP)', 'nenhuma', 'Amazon Web Services (AWS), Posit', 'Amazon Web Services (AWS), clickhouse', 'Cloud Própria, Huawei Cloud', 'Azure (Microsoft), Google Cloud (GCP), Oracle Cloud, Amazon Web Services (AWS)', 'Digital Ocean', 'Oracle Cloud, Cloud Própria, Google Cloud (GCP), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP), Oracle Cloud', '.', 'Servidores On Premise/Não utilizamos Cloud, Oracle Cloud', 'Servidores On Premise/Não utilizamos Cloud, Oracle Cloud, Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP)', 'Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Amazon Web Services (AWS)', 'Oracle Cloud, Azure (Microsoft), Amazon Web Services (AWS)', 'Google Cloud (GCP), Amazon Web Services (AWS), Cloud Própria, Azure (Microsoft)', 'Google Cloud (GCP), Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Amazon Web Services (AWS), Denodo', 'Snowflake', 'Azure (Microsoft), Denodo', 'IBM, Dremio', 'Cloud Própria, Google Cloud (GCP), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Azure (Microsoft), Oracle Cloud, Google Cloud (GCP)', 'Não uso', 'Azure (Microsoft), Oracle Cloud, Amazon Web Services (AWS), Google Cloud (GCP), Huawei', 'Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Azure (Microsoft)', 'DataBricks', 'Azure (Microsoft), Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Google Cloud (GCP)', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'Denodo', 'IBM, Google Cloud (GCP), Oracle Cloud', 'Onedrive', 'Amazon Web Services (AWS), Oracle Cloud, Google Cloud (GCP), Azure (Microsoft)', 'Oracle Cloud, Amazon Web Services (AWS)', 'Desconhecido', 'Amazon Web Services (AWS), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Algar', 'Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP), IBM', 'Azure (Microsoft), Cloud Própria, Google Cloud (GCP), Amazon Web Services (AWS)', 'Google Cloud (GCP), Protheus', 'Azure (Microsoft), Amazon Web Services (AWS), IBM', 'Amazon Web Services (AWS), Snowflake', 'Servidores On Premise/Não utilizamos Cloud, Oracle Cloud, Amazon Web Services (AWS)', 'IBM, Oracle Cloud, Azure (Microsoft)', 'Azure (Microsoft), GoodData', 'Empresa não usa cloud', 'Oracle Cloud, Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Oracle Cloud, Google Cloud (GCP)', 'SAP', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Google Cloud (GCP), Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Não utilizo atualmente', 'Oracle Cloud, Azure (Microsoft), Google Cloud (GCP)', 'Não utilizamos.', 'IBM, Azure (Microsoft), Oracle Cloud', 'Amazon Web Services (AWS), IBM, Google Cloud (GCP), Azure (Microsoft)', 'Servidores On Premise/Não utilizamos Cloud, HostDime', 'Oracle Cloud, Amazon Web Services (AWS), Google Cloud (GCP), Azure (Microsoft)', 'Nao utilizamos cloud', 'Azure (Microsoft), Amazon Web Services (AWS), Oracle Cloud, Google Cloud (GCP)', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, Oracle Cloud', 'Hostdime', 'Não utilizo Cloud no projeto', 'Não temos banco de dados', 'Azure (Microsoft), Datadricks', 'Oracle Cloud, Amazon Web Services (AWS), Google Cloud (GCP)', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Cloud Própria', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Cloud Própria', 'Google Cloud (GCP), Amazon Web Services (AWS), Magalu Cloud', 'Amazon Web Services (AWS), Azure (Microsoft), Cloud Própria', 'Azure (Microsoft), Amazon Web Services (AWS), Oracle Cloud', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, IBM', 'Cloud Própria, Oracle Cloud, UOL Host', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Cloudera', 'Sharepoint', 'Cloudera', 'Azure (Microsoft), OPENSHIFT', 'Azure (Microsoft), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Google Cloud (GCP), Cloud Própria, IBM, Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', '.Nenhuma', 'Servidores On Premise/Não utilizamos Cloud, Cloud QlikSense', 'Google Cloud (GCP), Azure (Microsoft), Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Ambiente próprio', 'Google Cloud (GCP), Oracle Cloud, Amazon Web Services (AWS), Azure (Microsoft)', 'Azure (Microsoft), Cloudera', 'Azure (Microsoft), Digital Ocean', 'não utilizamos CLOUD', 'Não uso cloud nem banco de dados.  Uso cluster e HPC', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), Databricks', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP)', 'Amazon Web Services (AWS), Salesforce', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), Cloud Própria', 'Amazon Web Services (AWS), IBM, Google Cloud (GCP)', 'Teradata Vantage', 'Google Cloud (GCP), Azure (Microsoft), Amazon Web Services (AWS), Oracle Cloud', 'Não utilizo nuvem', 'Google Cloud (GCP), Cloud Própria, Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'NENHUM', 'Amazon Web Services (AWS), Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud', 'SAP Business Technology Platform', 'Azure (Microsoft), Totvs cloud', 'Cloud Própria, Ativas', 'Azure (Microsoft), Onedrive', 'Azure (Microsoft), Cloud Própria, DB analytics e Salesforce', 'nda', 'Não atuo ainda nisso', 'CDP (Salesforce)', 'Não', 'OneDrive', 'Amazon Web Services (AWS), Cloud Própria, Google Cloud (GCP)', 'não sei', 'IBM, Google Cloud (GCP)', 'NSA', 'IBM, Amazon Web Services (AWS), Oracle Cloud, Google Cloud (GCP)', 'NENHUMA', 'Amazon Web Services (AWS), IBM, Azure (Microsoft)', 'Não utilizo nenhum', 'Amazon Web Services (AWS), databricks', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Cloud Própria', 'não sei informar', 'LocaWeb', 'Não utilizo cloud', 'Cloud Própria, Amazon Web Services (AWS), Google Cloud (GCP)', 'Cloud Própria, Governamental', 'Não trabalho utilizando Cloud', 'metabase', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Google Cloud (GCP)', 'Não utilizo ainda, estou em transição de carreira e estudando', 'Ñ usa', 'Nenhum desses', 'Amazon Web Services (AWS), Google Cloud (GCP), Azure (Microsoft), Oracle Cloud', 'No momento só fazendo cursos em casa.', 'IBM, Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Cloud Própria, Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Nemhuma', 'Amazon Web Services (AWS), Google Cloud (GCP), Oracle Cloud, Azure (Microsoft)', 'IBM, Oracle Cloud', 'Amazon Web Services (AWS), Google Cloud (GCP), Cloud Própria', 'Google Cloud (GCP), Amazon Web Services (AWS), Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Digital Ocean', 'Cloud Própria, Google Cloud (GCP), Amazon Web Services (AWS)', 'Planilhas', 'Não utilizo cloud no trabalho', 'Oracle Cloud, Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Azure (Microsoft)', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Google Cloud (GCP)', 'Google Cloud (GCP), OneDrive', 'Azure (Microsoft), Amazon Web Services (AWS), Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Cloud Própria', 'MicroStrategy', 'Não utilizamos cloud', 'Oracle Cloud, Cloud Própria, Azure (Microsoft), Amazon Web Services (AWS)', 'Servidores On Premise/Não utilizamos Cloud, Nenhuma', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), IBM', 'Amazon Web Services (AWS), Oracle Cloud, Azure (Microsoft), Google Cloud (GCP)', 'Google Cloud (GCP), Nenhuma das a', 'Não possui', 'Não atuo na área ainda', 'Outro', 'Cloud Própria, Nenhum', 'On premise', 'Azure (Microsoft), Informatica Cloud', 'Oracle Cloud, Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Amazon Web Services (AWS), Google Cloud (GCP)', 'Não tenho conhecimento de cloud', 'Azure , AWS no curso de formação de dados', 'Google Cloud (GCP), MongoDB Atlas', 'Oracle Cloud, Amazon Web Services (AWS), IBM, Google Cloud (GCP), Cloud Própria', 'Amazon Web Services (AWS), Dataiku', 'Local', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Azure (Microsoft)', 'Google Cloud (GCP), Azure (Microsoft), Cloud Própria', 'Azure (Microsoft), Amazon Web Services (AWS), IBM, Oracle Cloud, Cloud Própria', 'Naoutilizo', 'Não uso Cloud', 'Nsa', 'Spark', 'Nenhum dos citados acima', 'E-mail', 'one drive', 'Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Cloud Própria, IBM', 'Google Cloud (GCP), DeltaDNA', 'Azure (Microsoft), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud, Cloud Própria', 'nenhum acima', 'Google Cloud (GCP), Não atuo na area de dados na empresa ainda', 'Cloud Própria, Azure (Microsoft), Oracle Cloud', 'nada', 'Não se aplica', 'Google Cloud (GCP), Amazon Web Services (AWS), Confluent Cloud', 'Google Cloud (GCP), Amazon Web Services (AWS), Cloud Acadêmica', 'Outlook', 'Cloud Própria, Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP)', 'Seidor, Ativy', 'TOTVS Cloud', '...', 'One Drive', 'Cloud Própria, Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', 'Oracle Cloud, Cloud Própria, Amazon Web Services (AWS), Azure (Microsoft)', 'Amazon Web Services (AWS), Cloud interna', 'Google Cloud (GCP), Informatica Cloud', 'Servidores para Hospedagem (sites) Compartilhada', 'Servidores On Premise/Não utilizamos Cloud, Cloud Própria, Nuvem privada', 'Totovs Cloud', 'DropBox', 'Oracle Cloud, Cloud Própria, Azure (Microsoft)', 'Oracle Cloud, Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Servidores On Premise/Não utilizamos Cloud, Cloud Própria, Oracle Cloud', 'BTP', 'Cloud Própria, NENHUM', 'Azure (Microsoft), IBM, Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Oracle Cloud, Amazon Web Services (AWS), Google Cloud (GCP), IBM', 'Google Cloud (GCP), Amazon Web Services (AWS), Azure (Microsoft), Oracle Cloud', 'Oceano l)', 'IBM, Google Cloud (GCP), Amazon Web Services (AWS)', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Google Cloud (GCP), Azure (Microsoft)', 'Oracle Cloud, SAS', 'Amazon Web Services (AWS), Azure (Microsoft), Google Cloud (GCP), Oracle Cloud, Servidores On Premise/Não utilizamos Cloud', 'Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', 'IBM, Amazon Web Services (AWS), Google Cloud (GCP)', '-', 'Oracle Cloud, Google Cloud (GCP), Amazon Web Services (AWS)', 'Não trabalho com dados', 'Azure (Microsoft), Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP)', 'Não atuo ainda', 'Amazon Web Services (AWS), IBM, Servidores On Premise/Não utilizamos Cloud', 'Citrix', 'Oracle Cloud, IBM', 'Google Cloud (GCP), Cloud Própria, Azure (Microsoft)', 'Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud, IBM, DIGITAL OCEAN, LINODE', 'Servidores On Premise/Não utilizamos Cloud, Faitec', 'Sou estudante', 'Cloud Própria, Azure (Microsoft), Amazon Web Services (AWS)', 'Oracle Cloud, Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS)', 'Amazon Web Services (AWS), Google Cloud (GCP), Heroku', 'Azure (Microsoft), Amazon Web Services (AWS), Cloud Própria', 'Box', 'Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP), Amazon Web Services (AWS), Azure (Microsoft)', 'Cloud Própria, Amazon Web Services (AWS), Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Azure (Microsoft), IBM, Google Cloud (GCP), Cloud Própria', 'Azure (Microsoft), Google Cloud (GCP), Oracle Cloud', 'Cloud Própria, IBM', 'Oracle Cloud, Amazon Web Services (AWS), Azure (Microsoft)', 'Saveincloud / Jelastic', 'Google Cloud (GCP), Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft), Amazon Web Services (AWS)', 'Azure (Microsoft), Oracle Cloud, IBM', 'Oracle Cloud, Servidores On Premise/Não utilizamos Cloud, Azure (Microsoft)', 'Google Cloud (GCP), Amazon Web Services (AWS), IBM', 'Hue', 'Azure (Microsoft), Cloud Própria, Google Cloud (GCP)', 'Azure (Microsoft), Google Cloud (GCP), Amazon Web Services (AWS), Oracle Cloud', 'Azure (Microsoft), Hpcc', 'Azure (Microsoft), Google Cloud (GCP), Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Azure (Microsoft), Google Cloud (GCP), Cloud Própria', 'Google Cloud (GCP), Azure (Microsoft), Cloud Própria, Amazon Web Services (AWS)', 'Google Cloud (GCP), Azure (Microsoft), Oracle Cloud, Amazon Web Services (AWS)', 'Servidores On Premise/Não utilizamos Cloud, Google Cloud (GCP), Amazon Web Services (AWS), Cloud Própria', 'Sap analytics cloud', 'Servidores On Premise/Não utilizamos Cloud, Amazon Web Services (AWS), Google Cloud (GCP), Cloud Própria', 'Google Cloud (GCP), Azure (Microsoft), Cloud Própria, Servidores On Premise/Não utilizamos Cloud', 'Amazon Web Services (AWS), Cloud Própria, Servidores On Premise/Não utilizamos Cloud']

In [74]:
df_final['clouds_utilizadas'].isna().sum()

np.int64(9006)

In [75]:
# ==============================================================================
# ANÁLISE 8 (CORRIGIDA): Qual a popularidade das plataformas Cloud por ano?
# ==============================================================================
print("\n--- Gerando Análise 8 (Corrigida): Popularidade das Plataformas Cloud ---")

# --- ETAPA 1: Verificar se 'clouds_utilizadas' existe ---
if 'clouds_utilizadas' not in df_final.columns:
    print("!! Erro: Coluna 'clouds_utilizadas' não encontrada no DataFrame final. Análise de Cloud não pode ser feita.")
else:
    # --- ETAPA 2: Limpeza Preliminar e Criação das Colunas Individuais ---
    # Criamos uma cópia temporária para segurança
    df_temp_cloud = df_final[['ano', 'clouds_utilizadas']].copy()
    df_temp_cloud['clouds_utilizadas_str'] = df_temp_cloud['clouds_utilizadas'].fillna('Nenhuma').astype(str).str.lower()

    plataformas = {
        'usa_cloud_aws': 'aws|amazon web services',
        'usa_cloud_gcp': 'gcp|google cloud',
        'usa_cloud_azure': 'azure', # Usando só 'azure' para evitar conflito com 'microsoft'
        'usa_cloud_oracle': 'oracle cloud',
        'usa_cloud_ibm': 'ibm', # Simplificado
        'usa_cloud_propria': 'cloud própria|propria',
        'usa_cloud_on_premise': 'on premise|on-premise|servidores on premise',
    }

    print("Criando colunas individuais para cada plataforma Cloud...")
    for nome_coluna, keyword in plataformas.items():
        df_temp_cloud[nome_coluna] = df_temp_cloud['clouds_utilizadas_str'].str.contains(keyword, case=False, regex=True).astype(int)

    # --- ETAPA 3: Tratamento da categoria 'Nenhuma' ---
    keywords_nenhuma = [
        'nenhuma', 'não utilizo', 'nao utilizo', 'não usamos', 'nao usamos', 
        'não uso', 'nao uso', 'nada', 'non applicable', 'n/a', 'nda'
    ]
    df_temp_cloud['usa_cloud_nenhuma_explicit'] = df_temp_cloud['clouds_utilizadas_str'].str.contains('|'.join(keywords_nenhuma), case=False, regex=True).astype(int)
    soma_clouds = df_temp_cloud[[col for col in plataformas.keys()]].sum(axis=1)
    df_temp_cloud['usa_cloud_nenhuma_implicita'] = (soma_clouds == 0).astype(int)
    df_temp_cloud['usa_cloud_nenhuma'] = ((df_temp_cloud['usa_cloud_nenhuma_explicit'] == 1) | (df_temp_cloud['usa_cloud_nenhuma_implicita'] == 1)).astype(int)

    # --- ETAPA 4: Calcular a popularidade ---
    colunas_cloud_final = list(plataformas.keys()) + ['usa_cloud_nenhuma']
    
    # Agrupamos usando o DataFrame temporário
    popularidade_cloud = df_temp_cloud.groupby('ano')[colunas_cloud_final].sum()
    total_respondentes_ano = df_temp_cloud['ano'].value_counts()
    popularidade_cloud_pct = popularidade_cloud.div(total_respondentes_ano, axis=0).mul(100).round(2)

    # --- ETAPA 5: AJUSTE PARA 2023 - MARCAR COMO NaN ---
    # Verificamos se a coluna original 'clouds_utilizadas' era majoritariamente nula em 2023
    if df_final[df_final['ano'] == 2023]['clouds_utilizadas'].isnull().mean() > 0.95: # Se > 95% for nulo
        print("Detectado que dados de uso de Cloud para 2023 não estão disponíveis no mesmo formato. Marcando como NaN.")
        # Define a linha de 2023 como NaN (Not a Number), exceto talvez 'NENHUMA' se fizer sentido
        popularidade_cloud_pct.loc[2023, popularidade_cloud_pct.columns != 'NENHUMA'] = np.nan 
        # Você pode decidir se quer manter o 100% em Nenhuma ou colocar NaN em tudo
        # popularidade_cloud_pct.loc[2023, :] = np.nan # Opção: NaN em tudo para 2023
        
    # --- ETAPA 6: Limpeza dos Nomes das Colunas ---
    nomes_limpos_cloud = {
        col: col.replace('usa_cloud_', '').replace('_', ' ').upper() 
        for col in popularidade_cloud_pct.columns
    }
    popularidade_cloud_pct.rename(columns=nomes_limpos_cloud, inplace=True)

    print("\nTabela gerada (% de usuários por plataforma Cloud - 2023 ajustado):")
    print(popularidade_cloud_pct)

    # --- PREPARAÇÃO PARA O DASHBOARD ---
    popularidade_cloud_pct.to_csv(ANALISE_PARA_DASHBOARD/'09_analise_popularidade_cloud_pct.csv')

--- Gerando Análise 8 (Corrigida): Popularidade das Plataformas Cloud ---
Criando colunas individuais para cada plataforma Cloud...
Detectado que dados de uso de Cloud para 2023 não estão disponíveis no mesmo formato. Marcando como NaN.

Tabela gerada (% de usuários por plataforma Cloud - 2023 ajustado):
        AWS    GCP  AZURE  ORACLE   IBM  PROPRIA  ON PREMISE  NENHUMA
ano
2021  29.72  16.94  18.83    2.46  1.32     5.63       16.37    30.51
2022  28.80  20.84  19.62    2.25  1.36     4.66        9.58    33.69
2023    NaN    NaN    NaN     NaN   NaN      NaN         NaN      NaN
2024  30.36  20.13  21.26    2.76  1.15     3.66        8.87    32.85

##### Hipótese 09 respondida ✅

## KPI's 1

In [79]:
# ==============================================================================
print("--- Calculando KPIs: Salário Geral por Ano (Média e Mediana) ---")

# Usamos .agg() para calcular a média e a mediana de uma só vez
salario_geral_por_ano = df_final.groupby('ano')['salario_medio_mensal'].agg(['mean', 'median', 'count']).round(2)

# Renomeamos as colunas para clareza
salario_geral_por_ano.columns = ['salario_medio_geral', 'salario_mediano_geral', 'contagem']

print("Salário Geral (Média e Mediana) por Ano:")
print(salario_geral_por_ano)

--- Calculando KPIs: Salário Geral por Ano (Média e Mediana) ---
Salário Geral (Média e Mediana) por Ano:
      salario_medio_geral  salario_mediano_geral  contagem
ano
2021              9361.60                 7000.5      2365
2022              9714.50                 7000.5      3694
2023             10425.72                10000.5      4753
2024             11925.14                10000.5      4863

In [ ]:
salario_geral_por_ano.to_csv(ANALISE_PARA_DASHBOARD/'kpi_salario_geral_mediana_ano.csv') 
print(f"\n>> KPIs de Salário Geral (Média e Mediana) salvos em {ANALISE_PARA_DASHBOARD}/kpi_salario_geral_ano.csv'\n")

>> KPIs de Salário Geral (Média e Mediana) salvos em /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data/kpi_salario_geral_ano.csv'

In [ ]:
salario_medio_geral = df_final.groupby('ano')['salario_medio_mensal'].agg(['mean', 'median', 'count']).round(2)

# Renomeamos as colunas para clareza
salario_geral_por_ano.columns = ['salario_medio_geral', 'salario_mediano_geral', 'contagem']

print("Salário Geral (Média e Mediana) por Ano:")
print(salario_geral_por_ano)