In [15]:
import pandas as pd
from pathlib import Path
import sys

BASE_DIR = Path.cwd().parent
PROCESSED_DATA_DIR = BASE_DIR / 'data' / 'processed'
ANALISE_PARA_DASHBOARD = BASE_DIR / 'notebook' / 'dashboard_data'

# Carregando nosso dataset final, que é a única fonte de dados necessária a partir de agora
try:
    df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')
    print("Dataset final tratado carregado com sucesso!")
    print(f"Dimensões: {df_final.shape}")
except FileNotFoundError as e:
    print(f"Arquivo não encontrado {e}")

/tmp/ipykernel_20962/3018555840.py:11: DtypeWarning: Columns (1,5,6,7,23,24,26,27,29,30,36,37,43,69,73,74,85,97,112,113,122,146,148,149,151,152,161,167,171,181,203,205,218,229,269,282,297,345,361,370,371,372,373,374,375,376,418) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv(PROCESSED_DATA_DIR / 'dataset_final_tratado_para_analise.csv')

Dataset final tratado carregado com sucesso!
Dimensões: (17426, 525)

In [2]:
Path('dashboard_data').mkdir(exist_ok=True)
print("Pasta 'dashboard_data/' pronta para receber os arquivos de análise.")

Pasta 'dashboard_data/' pronta para receber os arquivos de análise.

In [3]:
df_final

,id_participante,data_envio,idade,faixa_idade,genero,etnia,pcd,experiencia_prejudicada,prejudicado_acredita_nao_ser_afetado,prejudicado_raca_etnia,...,usa_bi_viewb,usa_bi_wavefront,usa_bi_zoho,usa_bi_zoho_analytics,usa_bi_estudante,usa_bi_nda,usa_bi_nenhuma.1,usa_bi_nexbi,usa_bi_não_utilizo_ferramentas_de_bi_ainda,usa_bi_streamlit.1
0,reb94rv0msth7q4nreb94riaq80iz3yi,2024-10-16 11:19:17,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,1zc66g69jjt49y32l1zc66g8wqj79m4e,2024-10-16 20:45:31,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,uu99wmam4n5kc2uu99wmydf0rk7l58f7,2024-10-17 18:10:59,18.0,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,3ynsw7z0hl5hhpbfvaeqk73ynsw7z04l,2024-10-22 18:03:00,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,v6bji2ct5xckpl1uouv6bjiotkrf3b4f,2024-10-23 01:33:23,18.0,17-21,Masculino,Branca,Não,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17421,07nvo8cdy377a46gon207nvjebwe65zg,NaN,40.0,40-44,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17422,01mqnby32u01pg3nuj6vipp4mc06s8pg,NaN,27.0,25-29,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17423,01fncs8qbhl9zx01fncs8rqib2zl3d18,NaN,24.0,22-24,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17424,075h3v2z19if04yn7o075h3vhifl38rw,NaN,38.0,35-39,Masculino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17425,037usz1h2yip96dgil4mhj037uszw1gk,NaN,27.0,25-29,Feminino,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

## 1 - TABELA DE EVOLUÇÃO SALARIAL POR CARGO

In [10]:
print(df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack())

grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [12]:
evolucao_salario_cargo = df_final.groupby(['ano', 'grupo_cargo'])['salario_medio_mensal'].mean().round(2).unstack()

In [13]:
print('Tabela gerada: ')
print(evolucao_salario_cargo)

Tabela gerada:
grupo_cargo  Analista de BI  Analista de Dados  Analista de Negócios  \
ano
2021                6293.40            6779.81               7068.21
2022                6104.99            7148.38               7724.08
2023                6248.52            7138.87               7164.60
2024                6520.69            7998.93               8910.83

grupo_cargo  Cientista de Dados  Engenheiro de Analytics  Engenheiro de Dados  \
ano
2021                    9067.72                      NaN             10231.15
2022                    9933.95                 11186.22             10107.08
2023                   10534.71                 11040.07             11589.03
2024                   11822.92                 10873.31             12992.19

grupo_cargo  Engenheiro de ML  Gestão de Produto de Dados  \
ano
2021                 10042.16                    12750.50
2022                 14196.17                    11176.98
2023                 12507.17                    11346.18
2024                 15597.61                    11931.75

grupo_cargo  Não se aplica/Outra área   Outros
ano
2021                         14876.50  6795.02
2022                         16674.43  5465.91
2023                         17522.29  7313.53
2024                         19591.92  7454.51

In [33]:
evolucao_salario_cargo.to_csv(ANALISE_PARA_DASHBOARD/'analise_evolucao_salario_cargo.csv')
print(f'tabela evoluação salário por cargo criada e exportada para {ANALISE_PARA_DASHBOARD}')

tabela evoluação salário por cargo criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

## 2 - TABELA DE EVOLUÇÃO SALARIAL POR SENIORIDADE

In [23]:
evolucao_salario_senioridade = df_final.groupby(['ano', 'nivel_hierarquico'])['salario_medio_mensal'].mean().round(2).unstack()

In [28]:
evolucao_salario_senioridade

nivel_hierarquico   Júnior    Pleno    Sênior
ano
2021               3876.49  7609.92  12401.89
2022               3928.64  7961.82  12848.50
2023               3919.75  7533.55  13577.68
2024               4166.96  8048.79  14506.23

In [32]:
evolucao_salario_senioridade.reset_index().to_csv(ANALISE_PARA_DASHBOARD/'analise_evolucao_salario_senioridade.csv', index=False)
print(f'Tabela de evolução do salário médio por senioridade criada e exportada para {ANALISE_PARA_DASHBOARD}')

Tabela de evolução do salário médio por senioridade criada e exportada para /home/joao-vitor-w/Projects/PythonVscode/analise_state_of_data/notebook/dashboard_data

##### Pergunta "4" das hipóteses respondidas ✅

## 2 - TABELA DE POPULARIDADE DE LINGUAGENS USADAS POR ANO

In [37]:
colunas_linguagens = [col for col in df_final.columns if col.startswith('usa_linguagem_')]

In [38]:
colunas_linguagens

['usa_linguagem_net',
 'usa_linguagem_c_c++_c#',
 'usa_linguagem_java',
 'usa_linguagem_javascript',
 'usa_linguagem_julia',
 'usa_linguagem_matlab',
 'usa_linguagem_nenhuma',
 'usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho',
 'usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas',
 'usa_linguagem_php',
 'usa_linguagem_python',
 'usa_linguagem_r',
 'usa_linguagem_rust',
 'usa_linguagem_sas_stata',
 'usa_linguagem_sql',
 'usa_linguagem_scala',
 'usa_linguagem_visual_basic_vba']

In [44]:
popularidade_linguagens = df_final.groupby('ano')[colunas_linguagens].sum()

In [45]:
popularidade_linguagens

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,42,64,84,174,8,15,788,0,162,38,1346,306,0,77,1487,89,160
2022,33,52,106,194,6,25,1290,0,319,39,2089,385,0,123,2367,119,218
2023,40,70,113,282,8,30,1521,0,305,56,2825,401,7,151,3156,131,285
2024,31,46,94,223,6,20,1628,165,0,34,2935,342,12,130,3146,126,215

In [56]:
##porcentagem
total_respondentes_ano = df_final['ano'].value_counts()
popularidade_linguagensa_pct = popularidade_linguagens.div(total_respondentes_ano, axis=0).mul(100).round(2)

In [58]:
popularidade_linguagensa_pct

,usa_linguagem_net,usa_linguagem_c_c++_c#,usa_linguagem_java,usa_linguagem_javascript,usa_linguagem_julia,usa_linguagem_matlab,usa_linguagem_nenhuma,usa_linguagem_não_utilizo_linguagem_de_programação_no_trabalho,usa_linguagem_não_utilizo_nenhuma_das_linguagens_listadas,usa_linguagem_php,usa_linguagem_python,usa_linguagem_r,usa_linguagem_rust,usa_linguagem_sas_stata,usa_linguagem_sql,usa_linguagem_scala,usa_linguagem_visual_basic_vba
ano,,,,,,,,,,,,,,,,,
2021,1.59,2.42,3.18,6.58,0.30,0.57,29.79,0.00,6.12,1.44,50.89,11.57,0.00,2.91,56.22,3.36,6.05
2022,0.77,1.22,2.48,4.54,0.14,0.59,30.20,0.00,7.47,0.91,48.91,9.01,0.00,2.88,55.42,2.79,5.10
2023,0.76,1.32,2.13,5.33,0.15,0.57,28.74,0.00,5.76,1.06,53.37,7.58,0.13,2.85,59.63,2.47,5.38
2024,0.59,0.88,1.80,4.27,0.12,0.38,31.21,3.16,0.00,0.65,56.26,6.56,0.23,2.49,60.30,2.42,4.12

In [57]:
total_respondentes_ano

ano
2023    5293
2024    5217
2022    4271
2021    2645
Name: count, dtype: int64

In [60]:
popularidade_linguagensa_pct.to_csv(ANALISE_PARA_DASHBOARD/'analise_popularidade_linguagens_pct.csv')
print(f'Tabela gerada de % de uso da linguagem')

Tabela gerada de % de uso da linguagem

##### Pergunta número "8" das hipóteses respondida ✅